### ISSUE TITLE
Panasonic changed something again

### ISSUE THREAD

**Issue by nelsongraca** [sockless-coding/panasonic_cc#111]
as of now I'm getting this in the logs:

    2023-05-25 12:36:14.997 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
        result = await component.async_setup_entry(hass, self)
      File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
        devices = await hass.async_add_executor_job(api.get_devices)
      File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
        self.login()
      File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 108, in login
        self._get_groups()
      File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 183, in _get_groups
        raise ResponseError(response.status_code, response.text)
    custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 502 - Data: <html>
    <head><title>502 Bad Gateway</title></head>
    <body>
    <center><h1>502 Bad Gateway</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>

**Comment by JakobAaen** [comment]
Also having issues in general with Comfor Cloud, the app on Android also responds with errorcodes

**Comment by nelsongraca** [comment]
Ok so this is something om their side, it was never very stable.

I fear the day they kill it.

**Comment by JakobAaen** [comment]
My problems in HA started 09.06.36 GMT+2

**Comment by nelsongraca** [comment]
Working again, it was something with Panasonic servers.
