### ISSUE TITLE
Adapter Communication error code 5005

### ISSUE THREAD

**Issue by simplex303** [sockless-coding/panasonic_cc#113]
Home Assistant no longer has control of my HVAC.
Temperature and status is not being reported.

Turning on debug I get the below error message in logs when trying to change HVAC operating mode.

Running home assistant versions:
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/panasonic_cc/pcomfortcloud/session.py:420
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:04:57 PM (1 occurrences)
Last logged: 9:04:57 PM

[547516017872] Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/panasonic.py", line 21, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 351, in set_device
    self._api.set_device(
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 420, in set_device
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/panasonic_cc/climate.py", line 129, in async_set_hvac_mode
    await self._api.set_hvac_mode(hvac_mode)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 292, in set_hvac_mode
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/panasonic.py", line 24, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 351, in set_device
    self._api.set_device(
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 420, in set_device
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}

**Comment by simplex303** [comment]
After two weeks or so this problem has now fixed itself. HVAC status is now being reported. 
Must have been something on Panasonic's side.

**Comment by simplex303** [comment]
After two weeks or so this problem has now fixed itself. HVAC status is now being reported. 
Must have been something on Panasonic's side.
