### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by jonootto** [sockless-coding/panasonic_cc#13]
Hi, my integration stopped working, I've tried readding it, now it gives this error:

`2020-09-28 11:27:41 ERROR (MainThread) [custom_components.panasonic_cc.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 50, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 177, in get_devices
    for device in group['deviceIdList']:
KeyError: 'deviceIdList'`

**Comment by jonootto** [comment]
Updating resolved this
