### ISSUE TITLE
"Failed to setup" hard error even after full restart

### ISSUE THREAD

**Issue by pootle** [sockless-coding/panasonic_cc#131]
yesterday I added a new dashboard just for the A/C and it worked fine all day, but this morning I get this error always.
The integration summary shows 13 devices and 51 entities. I have tried reload from ... menu

`2023-09-26 10:36:19.345 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 10:36:19.348 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration panasonic_cc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 10:36:40.718 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-26 10:37:08.334 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0xFCDF:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:08.674 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0xFCDF:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:08.706 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0xFCDF:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:08.932 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3F4E:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:08.999 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3F4E:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:09.321 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3F4E:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:09.410 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x69B5:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:09.639 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x2D4D:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:10.152 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x2D4D:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:10.289 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x69B5:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:10.571 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x2D4D:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-09-26 10:37:10.662 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x69B5:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]`

**Comment by RonnieRocket2** [comment]
Same here

**Comment by RonnieRocket2** [comment]
Removed and tried to install gived this error

2023-09-27 10:05:07.682 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration panasonic_cc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-27 10:05:07.682 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-27 10:05:07.683 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration fusion_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-27 10:05:07.683 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-27 10:05:07.684 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-27 10:05:15.827 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-27 10:05:26.299 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Pool Shelly 2.5' for shelly integration not ready yet: DeviceConnectionError(TimeoutError()); Retrying in background
2023-09-27 10:15:41.384 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-27 10:15:54.225 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-27 10:18:52.001 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-27 10:21:54.117 WARNING (MainThread) [homeassistant.components.automation.turn_on_pool_pump_when_there_is_power] Solar Optimiser Pool Pump ON if Power Surplus: Already running
2023-09-27 10:23:18.085 WARNING (MainThread) [homeassistant.components.automation.test_to_be_continued] Lounge Cam Privacy when home: Already running
2023-09-27 10:36:50.843 WARNING (MainThread) [homeassistant.components.automation.turn_on_basement_fan_if_surplus] Solar Optimiser Basement Fan ON if Power Surplus : Already running
2023-09-27 10:59:53.451 WARNING (MainThread) [homeassistant.components.automation.turn_on_pool_pump_when_there_is_power] Solar Optimiser Pool Pump ON if Power Surplus: Already running
2023-09-27 11:21:57.497 WARNING (MainThread) [homeassistant.components.automation.turn_on_pool_pump_when_there_is_power] Solar Optimiser Pool Pump ON if Power Surplus: Already running
2023-09-27 11:22:20.495 WARNING (MainThread) [homeassistant.components.automation.turn_on_basement_fan_if_surplus] Solar Optimiser Basement Fan ON if Power Surplus : Already running
2023-09-27 11:22:35.494 WARNING (MainThread) [homeassistant.components.automation.turn_on_pool_pump_when_there_is_power] Solar Optimiser Pool Pump ON if Power Surplus: Already running
2023-09-27 11:23:28.489 WARNING (MainThread) [homeassistant.components.automation.turn_on_basement_fan_if_surplus] Solar Optimiser Basement Fan ON if Power Surplus : Already running
2023-09-27 11:24:13.482 WARNING (MainThread) [homeassistant.components.automation.turn_on_basement_fan_if_surplus] Solar Optimiser Basement Fan ON if Power Surplus : Already running
2023-09-27 11:24:27.475 WARNING (MainThread) [homeassistant.components.automation.turn_on_pool_pump_when_there_is_power] Solar Optimiser Pool Pump ON if Power Surplus: Already running
2023-09-27 11:27:39.458 WARNING (MainThread) [homeassistant.components.automation.turn_on_basement_fan_if_surplus] Solar Optimiser Basement Fan ON if Power Surplus : Already running
2023-09-27 11:27:52.458 WARNING (MainThread) [homeassistant.components.automation.turn_on_pool_pump_when_there_is_power] Solar Optimiser Pool Pump ON if Power Surplus: Already running
2023-09-27 11:38:03.427 WARNING (MainThread) [homeassistant.components.automation.turn_on_pool_pump_when_there_is_power] Solar Optimiser Pool Pump ON if Power Surplus: Already running
2023-09-27 11:43:25.286 WARNING (MainThread) [homeassistant.components.automation.turn_on_water_heater_if_lots_of_excess_power] Solar Optimiser Water Heater ON if Power Surplus: Already running
2023-09-27 12:21:42.391 WARNING (MainThread) [homeassistant.components.automation.turn_on_water_heater_if_lots_of_excess_power] Solar Optimiser Water Heater ON if Power Surplus: Already running
2023-09-27 15:30:23.756 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2023-09-27 15:41:13.738 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2023-09-27 15:49:45.631 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-27 15:50:20.357 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-27 16:11:24.844 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-09-27 16:11:53.065 ERROR (MainThread) [custom_components.panasonic_cc.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"code":4101,"message":"Login ID or password is incorrect,or account is locked"}
2023-09-27 16:12:10.442 ERROR (MainThread) [custom_components.panasonic_cc.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"code":4101,"message":"Login ID or password is incorrect,or account is locked"}
2023-09-27 16:13:55.541 ERROR (MainThread) [custom_components.panasonic_cc.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}

**Comment by codyc1515** [comment]
429 Too many requests error looks like Panasonic Cloud denying your HA. I would disable the integration, wait for a bit then try again.

**Comment by sockless-coding** [comment]
Hi @pootle and @RonnieRocket2 
How many HVAC devices do you have connected to that account? Also, do you have other thing monitoring your HVACs the Panasonic API has a rate limit per IP. So if too many things in your network (or if you have a shared public ip) is accessing the API the IP will get blocked for X amount of time.

**Comment by RonnieRocket2** [comment]
> Hi @pootle and @RonnieRocket2 How many HVAC devices do you have connected to that account? Also, do you have other thing monitoring your HVACs the Panasonic API has a rate limit per IP. So if too many things in your network (or if you have a shared public ip) is accessing the API the IP will get blocked for X amount of time.

We have 2 Aircon units on the account and notthing else monitoring HVACs. All working fine here for now after your recent modification.

**Comment by pootle** [comment]
Yes I think that it, I have 13 units. Even the app sometimes does a lock out. Idiotic software

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
