### ISSUE TITLE
Panasonic comfort cloud non funziona

### ISSUE THREAD

**Issue by massitate** [sockless-coding/panasonic_cc#134]
Buongiorno da questa mattina dopo l'aggiornamento di home Assistant 2023.10.2 di ieri non funziona più ovvero non si connette al cloud di panasonic. Da app Panasonic nessun problema. E' successo qualcosa a cui si può rimediare? grazie.

**Comment by massitate** [comment]
Confermo che deve essere un problema di aggiornamento HA perché controllando bene è da ieri sera alle 21.00 che ha smesso di funzionare ora in cui ho fatto l'aggiornamento Ha.

**Comment by massitate** [comment]
da questo errore
Logger: homeassistant.config_entries
Source: config_entries.py:565
First occurred: 07:48:06 (1 occurrences)
Last logged: 07:48:06

Error unloading entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 102, in async_unload_entry
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

**Comment by massitate** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/panasonic_cc/sensor.py:142
Integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 10:43:32 (2 occurrences)
Last logged: 10:43:32

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1187, in _async_registry_updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/sensor.py", line 142, in state
    return round(self._api.daily_energy,2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type NoneType doesn't define __round__ method

**Comment by massitate** [comment]
Scusa se insisto riuscirebbe in qualche maniera aiutarmi a ripristinare l'integrazione di Panasonic che fino a ieri funzionava benissimo grazie anticipatamente.

**Comment by codyc1515** [comment]
I believe this should be sorted now.
