### ISSUE TITLE
Unexpected error creating device. DB system error due to db system

### ISSUE THREAD

**Issue by maidiries** [sockless-coding/panasonic_cc#150]
![image](https://github.com/sockless-coding/panasonic_cc/assets/61229406/0a08d826-6ae3-45a7-8b2e-2ae11ee30a28)

After Login, always this error: Unexpected error creating device.

Have deleted from HA and try to reinstall got this error now.
Previous HA versions it works.

```
Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}
```

Similar issue:
https://github.com/sockless-coding/panasonic_cc/issues/147

----
Home Assistant:
Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Interfície d'usuari 20231208.2

**Comment by sybri** [comment]
the same

**Comment by mchacher** [comment]
same for me. I don't think it is a regional issue. I am in France.
My account was banned yesterday, now only the mobile app is ok

**Comment by Strohhutpat** [comment]
same for me.

**Comment by jellewie** [comment]
Same error for me (The Netherlands). 

I can still control them using the OEM android app

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 19:01:07 (5 occurrences)
Last logged: 22:26:54

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}

**Comment by bboyblank** [comment]
Same issue, I did find after updating HA to 2023.12.1 it broke after this.

**Comment by kavetheman** [comment]
I have the same problem with latest version of ha

**Comment by mstendah** [comment]
Now I cannoy even add the integration back. Eariel it asked me for my credentials and failed after that. Now it does not even ask for credentials. It simply throws me back to the integration repository.

**Comment by lpmitbenji** [comment]
I have the same problem. is after the HA update to 2023.12.1

**Comment by jawilczek** [comment]
I have the same problem. fresh installation of HA 2023.12.1.

**Comment by acailley** [comment]
same here :
`2023-12-13 00:50:47.585 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}`

**Comment by TimBE1989** [comment]
Same issue for me.

**Comment by syepes** [comment]
Same issue with 2023.12.2

**Comment by djmaxim1981** [comment]
same issue for me.


This error originated from a custom integration.

Logger: custom_components.panasonic_cc.config_flow
Source: custom_components/panasonic_cc/config_flow.py:60
Integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 1:18:27 PM (1 occurrences)
Last logged: 1:18:27 PM

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}

**Comment by mstendah** [comment]
Is downgrading some HA components a workaround for this?

**Comment by eriklook-prog** [comment]
> Is downgrading some HA components a workaround for this?

Tried this already. No change, same error.

**Comment by hanselot76** [comment]
The update fixed the issue here as well :)

**Comment by MetalOctopus** [comment]
What was the fix for this in the end?

**Comment by MetalOctopus** [comment]
For people on Home Assistant where this update hasn't yet come through on HACS:

Find session.py by:
`pip show pcomfortcloud`
will get something like: /usr/local/lib/python3.11/site-packages/

`nano /usr/local/lib/python3.11/site-packages/pcomfortcloud/session.py`
find `"language": "0"` on line 125. 
Replace with `"language": 0`

save, reboot, you should be back online.

**Comment by dardour7** [comment]
Yes @MetalOctopus it's works thank you

**Comment by jellewie** [comment]
With a new version (from HACS) and a reboot. My issues are **solved** again.

**Comment by codyc1515** [comment]
Please close the issue.

**Comment by Sanitytheman** [comment]
Hi all, i get this now, what should i do ?

**Comment by julianbeere** [comment]
Updated HA this morning and now get the "Unexpected error creating device." error... anyone else?

**Comment by LU524** [comment]
Same

**Comment by aceindy** [comment]
Work in progress on pcomfort library,see here
https://github.com/sockless-coding/panasonic_cc/issues/191#issuecomment-2179220649
