### ISSUE TITLE
No Connection since 05:00 AM

### ISSUE THREAD

**Issue by tonimant** [sockless-coding/panasonic_cc#167]
Hello, 
Does there is a Problem with the intergration? 
There ist no Login possible anymore. 
Does someone has the same issue ? 

Thank you for support. 

Greetings

**Comment by codyc1515** [comment]
Did you enable two-factor authentication?

**Comment by tonimant** [comment]
Hey Thank for the reply. No I don‘t enable it.

**Comment by tonimant** [comment]
`Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 06:17:52 (4 occurrences)
Last logged: 07:14:27

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: `

**Comment by tonimant** [comment]
> Did you enable two-factor authentication?

No I don't. 
Should I do it ?

**Comment by codyc1515** [comment]
No. Sorry, not immediately sure what your issue might be.
