### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by MorVes** [sockless-coding/panasonic_cc#180]
Log details (ERROR)
This error originated from a custom integration.
Logger: homeassistant
Source: custom_components/panasonic_cc/sensor.py:142
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 14:17:22 (10 occurrences)
Last logged: 14:21:50

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1010, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 963, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/sensor.py", line 142, in state
    return round(self._api.daily_energy,2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type NoneType doesn't define __round__ method

**Comment by sockless-coding** [comment]
Fixed
