### ISSUE TITLE
This custom component doesn't work anymore "Unexpected error creating device" 

### ISSUE THREAD

**Issue by dariozulu** [sockless-coding/panasonic_cc#194]
Hello,
Some days ago, my panasonic etherea clima disappeared from dashboard. I try to remove and reinstall the custom component from home assistant restarting at every steps but now when I try to add the clima configuring the "panasonic comfort cloud" from integrations it say me:
  "Unexpected error creating device".
Please Is there someone can help me to resolve this problem.
Thank you so much for any tips.

**Comment by Auka84** [comment]
Hey @dariozulu   Yep, it's for everybody, i have the same ;). follow this https://github.com/sockless-coding/panasonic_cc/issues/191

they are busy on it :)

**Comment by autumnleaf73** [comment]
I've got the same problem

**Comment by kongjudas** [comment]
It happened to me today, but has been working until a few hours ago. Can it be that Panasonic is rolling out some update stuff..?

**Comment by dariozulu** [comment]
I am very thankful to this custom component developer for his very fast work (a couple of days) of updating and resolve the issue so now everything has come back to work perfectly. Thanks again!!

**Comment by djmaxim1981** [comment]
Thank you so much for working on this custom component - all functions are working again for me except the "swing" function. I keep getting this error message when i'm changing the swing mode (up|down|mid|auto) - none of it work. Works fine on the ComfortCloud app.

Error Msg "Failed to call service climate/set_swing_mode. 'coroutine' object is not subscriptable"




**Logs**

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:29:28 AM (2 occurrences)
Last logged: 10:30:36 AM

[546707358272] Unexpected exception
[545954550848] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/panasonic.py", line 341, in set_device
    await self._api.set_device(
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 154, in set_device
    if device and device['parameters']['airSwingHorizontal'].value == -1:
                  ~~~~~~^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 751, in async_handle_set_swing_mode_service
    await self.async_set_swing_mode(swing_mode)
  File "/config/custom_components/panasonic_cc/climate.py", line 176, in async_set_swing_mode
    await self._api.set_swing_mode(swing_mode)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 303, in set_swing_mode
    await self.set_device(
  File "/config/custom_components/panasonic_cc/panasonic.py", line 347, in set_device
    await self._api.set_device(
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 154, in set_device
    if device and device['parameters']['airSwingHorizontal'].value == -1:
                  ~~~~~~^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not subscriptable

**Comment by danielcherubini** [comment]
https://github.com/sockless-coding/panasonic_cc/pull/199 Fixes this

**Comment by kellyatkinson** [comment]
@dariozulu can you please mark this issue as closed (as it duplicates an earlier issue which is being heavily worked on) so the community can focus on fixes? Cheers!

**Comment by sockless-coding** [comment]
Fixed
