### ISSUE TITLE
Cannot add integration "Invalid Handler Specified"

### ISSUE THREAD

**Issue by kusius** [sockless-coding/panasonic_cc#202]
Hello, Im trying to add the integration and I receive a popup that says 

Config flow could not be loaded: {"message":"Invalid handler specified"}

![image](https://github.com/sockless-coding/panasonic_cc/assets/5391706/814a842e-ae0a-4d8d-a542-0ca33b4571bc)

Relevant logs

2024-06-22 11:54:31.008 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.panasonic_cc.config_flow
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/panasonic_cc/__init__.py", line 16, in <module>
from .const import (
File "/config/custom_components/panasonic_cc/const.py", line 63, in <module>
ClimateEntityFeature.TURN_OFF |
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
raise AttributeError(name) from None
AttributeError: TURN_OFF
2024-06-22 11:54:31.045 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration panasonic_cc: Exception importing custom_components.panasonic_cc.config_flow

**Comment by jaknil0** [comment]
I get this as well. Cant add 40, 41, 42, 43.

Not getting this issue with previous versions.

**Comment by sockless-coding** [comment]
Can you log in to the app with the credentials or are you getting the Multifactor setup step, if you are getting the MF step you need to complete that first.

**Comment by jaknil0** [comment]
@sockless-coding first of all, thanks for an epic custom component! 

I performed the MF step again before attempting to upgrade. Was always able to use the app without issues. I tried downgrading to version 39 and then upgrading again, no luck. Then i upgraded HA to latest stable from 2023 something. After upgrade to latest HA i was able to add the integration without issues.

**Comment by timovp** [comment]
I experience the same error and I have never entered my credentials before in the app, its the first time using it for me, so i suspect the MFA issue cant be the thing causing it...

**Comment by timovp** [comment]
My issue was solved by upgrading home-assistant itself. 👍

**Comment by kusius** [comment]
@timovp Thanks. Will try to update again and see. Hoping to close the issue if it works.

You updated to the latest HA? What version?

**Comment by sockless-coding** [comment]
@kusius I think the integration needs at least 2024.4 to work, I'm not entirely sure when they introduced all the new state constants.
