### ISSUE TITLE
Can't set Boost/Eco mode since 1.0.49

### ISSUE THREAD

**Issue by pdm1976** [sockless-coding/panasonic_cc#227]
Besides the issue of #225 where NanoeX can't be enabled, I also have an issue where I can't change the mode to Boost or Eco. I have seen that:
1. I can select the mode in HA but nothing really happens ( as checked by using the original app)
2. I can select the mode in HA but it jumps back to 'none' 

On the HA mobile app I once got an onscreen error:

![Screenshot_HA](https://github.com/sockless-coding/panasonic_cc/assets/11557121/7d337b3c-ba09-4afc-8fd9-41cc9524e38d)

Further the logs show nothing relating to this. The debug log however shows the below:

2024-06-28 16:45:41.061 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] POST url: https://accsmart.panasonic.com/deviceHistoryData, data: {'deviceGuid': 'CS-Z35ZKEW+E064827608', 'dataMode': 2, 'date': '20240628', 'osTimezone': '+02:00'}, response: {"temperatureUnit":0,"deviceRegisterTime":"20240529","historyDataList":[{"dataTime":"20240601","averageSettingTemp":22,"averageInsideTemp":21.642105263157895,"averageOutsideTemp":-255,"consumption":0.023000000000000013,"cost":0.00736,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240602","averageSettingTemp":20.659574468085108,"averageInsideTemp":20.893617021276597,"averageOutsideTemp":-255,"consumption":0.033000000000000015,"cost":0.010560000000000007,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240603","averageSettingTemp":22,"averageInsideTemp":21.479166666666668,"averageOutsideTemp":16.8,"consumption":0.202,"cost":0.07622,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240604","averageSettingTemp":23,"averageInsideTemp":21.28125,"averageOutsideTemp":21.0625,"consumption":0.3900000000000001,"cost":0.14765999999999999,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240605","averageSettingTemp":22.932291666666668,"averageInsideTemp":20.364583333333332,"averageOutsideTemp":16.727272727272727,"consumption":0.3760000000000001,"cost":0.14233999999999994,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240606","averageSettingTemp":23,"averageInsideTemp":20.989583333333332,"averageOutsideTemp":18.714285714285715,"consumption":0.43700000000000017,"cost":0.16551999999999992,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240607","averageSettingTemp":22.71875,"averageInsideTemp":21.260416666666668,"averageOutsideTemp":20.57894736842105,"consumption":0.7440000000000002,"cost":0.28218000000000004,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240608","averageSettingTemp":23,"averageInsideTemp":22.5625,"averageOutsideTemp":12.454545454545455,"consumption":0.09000000000000002,"cost":0.028800000000000013,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240609","averageSettingTemp":21.926315789473684,"averageInsideTemp":21.778947368421054,"averageOutsideTemp":20.88888888888889,"consumption":0.7650000000000001,"cost":0.24479999999999988,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240610","averageSettingTemp":22.005208333333332,"averageInsideTemp":21.302083333333332,"averageOutsideTemp":13.785714285714286,"consumption":0.25599999999999995,"cost":0.09674,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240611","averageSettingTemp":22.416666666666668,"averageInsideTemp":20.072916666666668,"averageOutsideTemp":16.352941176470587,"consumption":0.31500000000000006,"cost":0.11916000000000003,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240612","averageSettingTemp":23.057291666666668,"averageInsideTemp":20.96875,"averageOutsideTemp":14.222222222222221,"consumption":0.138,"cost":0.05189999999999999,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240613","averageSettingTemp":22.989583333333332,"averageInsideTemp":20.958333333333332,"averageOutsideTemp":18.137931034482758,"consumption":0.6600000000000003,"cost":0.2502599999999999,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240614","averageSettingTemp":23,"averageInsideTemp":21.854166666666668,"averageOutsideTemp":17.857142857142858,"consumption":0.040000000000000015,"cost":0.014660000000000003,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240615","averageSettingTemp":22.86842105263158,"averageInsideTemp":20.894736842105264,"averageOutsideTemp":18,"consumption":0.11900000000000001,"cost":0.03808000000000001,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240616","averageSettingTemp":21.583333333333332,"averageInsideTemp":20.104166666666668,"averageOutsideTemp":19.416666666666668,"consumption":0.4730000000000001,"cost":0.15135999999999994,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240617","averageSettingTemp":20.67058823529412,"averageInsideTemp":20.235294117647058,"averageOutsideTemp":20.571428571428573,"consumption":0.23,"cost":0.08692000000000001,"heatConsumptionRate":0,"coolConsumptionRate":0.7739130434782608,"heatCostRate":0,"coolCostRate":0.7781868384721583},{"dataTime":"20240618","averageSettingTemp":22.40625,"averageInsideTemp":20.989583333333332,"averageOutsideTemp":20,"consumption":0.32300000000000006,"cost":0.12208000000000001,"heatConsumptionRate":0,"coolConsumptionRate":0.8049535603715169,"heatCostRate":0,"coolCostRate":0.809305373525557},{"dataTime":"20240619","averageSettingTemp":23.5,"averageInsideTemp":21.45744680851064,"averageOutsideTemp":20.214285714285715,"consumption":0.6170000000000003,"cost":0.23397999999999988,"heatConsumptionRate":0,"coolConsumptionRate":0.9367909238249594,"heatCostRate":0,"coolCostRate":0.9387127104880764},{"dataTime":"20240620","averageSettingTemp":23.5,"averageInsideTemp":22.05263157894737,"averageOutsideTemp":-255,"consumption":0.042000000000000016,"cost":0.015420000000000003,"heatConsumptionRate":0,"coolConsumptionRate":0,"heatCostRate":0,"coolCostRate":0},{"dataTime":"20240621","averageSettingTemp":23.5,"averageInsideTemp":22.03191489361702,"averageOutsideTemp":17.571428571428573,"consumption":0.159,"cost":0.059939999999999986,"heatConsumptionRate":0,"coolConsumptionRate":0.8238993710691824,"heatCostRate":0,"coolCostRate":0.8304971638304973},{"dataTime":"20240622","averageSettingTemp":22.911458333333332,"averageInsideTemp":21.21875,"averageOutsideTemp":16.375,"consumption":0.21900000000000003,"cost":0.07008000000000002,"heatConsumptionRate":0,"coolConsumptionRate":0.7442922374429223,"heatCostRate":0,"coolCostRate":0.7442922374429223},{"dataTime":"20240623","averageSettingTemp":22.208333333333332,"averageInsideTemp":21.583333333333332,"averageOutsideTemp":24.464285714285715,"consumption":0.8400000000000004,"cost":0.26879999999999993,"heatConsumptionRate":0,"coolConsumptionRate":0.930952380952381,"heatCostRate":0,"coolCostRate":0.9309523809523813},{"dataTime":"20240624","averageSettingTemp":22.666666666666668,"averageInsideTemp":21.9375,"averageOutsideTemp":27.348837209302324,"consumption":2.4569999999999994,"cost":0.9331200000000001,"heatConsumptionRate":0,"coolConsumptionRate":0.9796499796499797,"heatCostRate":0,"coolCostRate":0.9802169067215364},{"dataTime":"20240625","averageSettingTemp":22.015625,"averageInsideTemp":21.364583333333332,"averageOutsideTemp":29.019607843137255,"consumption":3.4139999999999993,"cost":1.29678,"heatConsumptionRate":0,"coolConsumptionRate":0.9730521382542475,"heatCostRate":0,"coolCostRate":0.973457332778112},{"dataTime":"20240626","averageSettingTemp":22.161458333333332,"averageInsideTemp":22,"averageOutsideTemp":29.92,"consumption":3.1100000000000003,"cost":1.1812599999999998,"heatConsumptionRate":0,"coolConsumptionRate":0.9836012861736335,"heatCostRate":0,"coolCostRate":0.9840509286693869},{"dataTime":"20240627","averageSettingTemp":21.963541666666668,"averageInsideTemp":22.083333333333332,"averageOutsideTemp":27.545454545454547,"consumption":3.867999999999999,"cost":1.4693000000000005,"heatConsumptionRate":0,"coolConsumptionRate":0.9940537745604967,"heatCostRate":0,"coolCostRate":0.9944191111413594},{"dataTime":"20240628","averageSettingTemp":22.393939393939394,"averageInsideTemp":21.40909090909091,"averageOutsideTemp":21.423076923076923,"consumption":0.8410000000000002,"cost":0.31915999999999994,"heatConsumptionRate":0,"coolConsumptionRate":0.9548156956004756,"heatCostRate":0,"coolCostRate":0.9560721894974308},{"dataTime":"20240629","averageSettingTemp":-255,"averageInsideTemp":-255,"averageOutsideTemp":-255,"consumption":-255,"cost":-255},{"dataTime":"20240630","averageSettingTemp":-255,"averageInsideTemp":-255,"averageOutsideTemp":-255,"consumption":-255,"cost":-255}],"electricRate":{"weekdayBaseRate":0.38,"currency":"Eur","weekendBaseRate":0.32,"weekendDifferentRateTime":[],"weekdayDifferentRateTime":[{"rate":0.32,"time":[{"startTime":"22:00","endTime":"7:00"}]}]}}
2024-06-28 16:45:41.348 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/C666151286, response: {"timestamp":1719585941175,"permission":3,"summerHouse":0,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":true,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":1,"operate":0,"operationMode":4,"temperatureSet":26,"fanSpeed":5,"fanAutoMode":1,"airSwingUD":0,"airSwingLR":2,"airDirection":1,"ecoMode":0,"ecoNavi":1,"nanoe":2,"iAuto":1,"insideTemperature":24,"outTemperature":24,"airQuality":0},"deviceNanoe":1}
2024-06-28 16:45:41.349 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Data: <custom_components.panasonic_cc.pcomfortcloud.panasonicdevice.PanasonicDevice object at 0x7f4ac8560bc0>
2024-06-28 16:45:42.410 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/CS-Z71ZKEW%2BE065102012, response: {"timestamp":1719585942274,"permission":3,"summerHouse":0,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":true,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":true,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":0,"insideCleaning":1,"fireplace":0,"lastSettingMode":0,"operate":0,"operationMode":2,"temperatureSet":23.5,"fanSpeed":0,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":0,"ecoMode":2,"ecoNavi":0,"nanoe":2,"iAuto":0,"airDirection":0,"insideTemperature":23,"outTemperature":126,"airQuality":0},"deviceNanoe":3}
2024-06-28 16:45:42.411 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Data: <custom_components.panasonic_cc.pcomfortcloud.panasonicdevice.PanasonicDevice object at 0x7f4ac85489b0>
2024-06-28 16:45:43.433 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Set AC Office ecomode boost
2024-06-28 16:45:46.136 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] POST url: https://accsmart.panasonic.com/deviceStatus/control, data: {'deviceGuid': 'CS-Z35ZKEW+E064827608', 'parameters': {'operate': 1}}, response: {"result":0}
2024-06-28 16:45:48.104 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/CS-Z35ZKEW%2BE064827608, response: {"timestamp":1719585947946,"permission":3,"summerHouse":0,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":true,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":true,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":0,"insideCleaning":1,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":23,"fanSpeed":2,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":2,"ecoMode":0,"ecoNavi":0,"nanoe":2,"iAuto":0,"airDirection":0,"insideTemperature":21,"outTemperature":27,"airQuality":0},"deviceNanoe":3,"visualizationAvlFlg":true,"simulationShowFlg":true,"simulationSettingFlg":true,"simulationSettings":{"no":43,"shapeId":0,"positionId":0,"widthId":0,"levelGroup":[120,300,720],"devPositionTypeId":0,"nanoeOnTime":19168}}
2024-06-28 16:45:48.105 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Data: <custom_components.panasonic_cc.pcomfortcloud.panasonicdevice.PanasonicDevice object at 0x7f4ac7c81ca0>

I tried to reload the integration which does not help. I am on all the latest versions. I noticed no issues before 1.0.49.

**Comment by sockless-coding** [comment]
Should be fixed in v1.0.50

**Comment by pdm1976** [comment]
That is great work! Thank you. I will check it out first thing tomorrow.

**Comment by codyc1515** [comment]
On the very latest versions

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:364
integration: Switch (documentation, issues)
First occurred: 23:47:38 (2 occurrences)
Last logged: 23:54:00

Error while setting up panasonic_cc platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/panasonic_cc/switch.py", line 30, in async_setup_entry
    if device.support_eco_navi:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/panasonic.py", line 274, in support_eco_navi
    return self._details.features.eco_navi
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'features'

**Comment by codyc1515** [comment]
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:598
integration: Climate (documentation, issues)
First occurred: 23:47:37 (2 occurrences)
Last logged: 23:54:00

Error adding entity None for domain climate with platform panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 816, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 318, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 500, in capability_attributes
    data[ATTR_PRESET_MODES] = self.preset_modes
                              ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 318, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/climate.py", line 231, in preset_modes
    return self._api.available_presets
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/panasonic.py", line 308, in available_presets
    if self._details.features.quiet_mode:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'features'

**Comment by lltr** [comment]
```
Logger: homeassistant.loader
Source: custom_components/panasonic_cc/const.py:69
Integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 7:56:29 PM (1 occurrences)
Last logged: 7:56:29 PM
Unexpected exception importing component custom_components.panasonic_cc

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/panasonic_cc/__init__.py", line 16, in <module>
    from .const import (
  File "/config/custom_components/panasonic_cc/const.py", line 69, in <module>
    ClimateEntityFeature.TURN_OFF |
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF
```

1.0.54

**Comment by sockless-coding** [comment]
@codyc1515 strange that the device details isn't available, I'll add a None check

@lltr what HA version are you running?

**Comment by lltr** [comment]
> @codyc1515 strange that the device details isn't available, I'll add a None check
> 
> @lltr what HA version are you running?

 Home Assistant 2023.9.2 Supervisor 2024.06.2 Operating System 10.3 Frontend 20230911.0 - latest

**Comment by lltr** [comment]
> > @codyc1515 strange that the device details isn't available, I'll add a None check
> > @lltr what HA version are you running?
> 
> Home Assistant 2023.9.2 Supervisor 2024.06.2 Operating System 10.3 Frontend 20230911.0 - latest

Worked after updating my HA version.

**Comment by pdm1976** [comment]
@sockless-coding Thank you very much. All ok again!
