### ISSUE TITLE
Home Assistant Tells me No Devices

### ISSUE THREAD

**Issue by Csejka** [sockless-coding/panasonic_cc#234]
Hi there,

after Updating my Home Assistant and all Plugins to the newest Version and also Adding 2FA to my Panasonic Comfort Cloud i cant get the plugin back working again.

When i try to login to my Account within the Plugin it tells me No Devices Found - In the Comfort Cloud App i have my 2 Air Conditions inside.

Can anybody help me ? 

Best Beni

**Comment by sockless-coding** [comment]
Enable debug logging and l need the entry that looks like:
`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group ...`

**Comment by Csejka** [comment]
i cant find this line in any log - maybe this is because if i add the integrations and fill in my credentials it dont give me an error it only says that there are no devices found and i also dont have the integration afterwords in the integrations tab.

**Comment by sockless-coding** [comment]
What type of devices is it, because that api call doesn't return any...

**Comment by Csejka** [comment]
Panasonic CS-TZ25WKEW

Panasonic CS-TZ35WKEW

**Comment by sockless-coding** [comment]
And the credentials you entered in HA have access to them?

**Comment by Csejka** [comment]
for sure i have this two air cons in my CC account and can access them over the app

i had my air cons working with your plugin the last 2 years --> it suddenly stopped after updates on your component and HA side

**Comment by sockless-coding** [comment]
The problem is most likely on the Panasonic side... try renaming your group in the app, restart HA and look for the `groupName` device group request.

**Comment by Csejka** [comment]
i tried this My House but no success

**Comment by sockless-coding** [comment]
So you renamed the group in the app to something else, but the log entry still said 'My House'?

**Comment by Csejka** [comment]
i made a new group - restartet home assistant Name of the Group is Home and when i want to login to the integrations it gives me that again 

2024-06-29 20:38:22.126 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: {"uiFlg":false,"groupCount":1,"groupList":[{"groupId":348643,"groupName":"My House","pairingList":[],"deviceList":[]}]}

**Comment by codyc1515** [comment]
Have you set-up a separate account that does not have access to your devices? Try confirming that you are using the same login for HA and the app and seeing the same in the app with the same login.

**Comment by Master-Atreides** [comment]
Hi all,

Don't know if this is related or whether I should pile in on another thread, but after the fix over a week ago, the integration went down again this morning. I have since updated to v1.0.65

**Comment by heldchen** [comment]
@Master-Atreides not related. there are other issues for that.

**Comment by Master-Atreides** [comment]
Ok. Thanks. I'll try and find the right thread.

Kindly,  Shannon

Sent on the go with Vodafone
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by asatron1** [comment]
Hi,
after update from 1.0.56 to 1.0.58. i have the same problem.
rename the groupname in the app an a reboot changes nothing

![image](https://github.com/sockless-coding/panasonic_cc/assets/129151323/0643fa5d-4ca8-41aa-abe3-f71ba6ef6c2b)

**Comment by Csejka** [comment]
yeah - i still have the problem

**Comment by asatron1** [comment]
`2024-07-02 15:20:46.311 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Starting Session
2024-07-02 15:20:46.314 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Loaded settings from '/root/.panasonic-settings'
2024-07-02 15:20:46.317 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Access token is valid
2024-07-02 15:20:47.124 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: {"uiFlg":false,"groupCount":1,"groupList":[{"groupId":1122045,"groupName":"Zuhause","pairingList":[],"deviceList":[{"deviceGuid":"CS-Z35ZKEW+E064818781","deviceType":"3","deviceName":"Wohnzimmer ","permission":3,"temperatureUnit":0,"summerHouse":0,"nanoeStandAlone":true,"autoMode":true,"modeAvlList":{"autoMode":1},"parameters":{"operate":0,"operationMode":2,"temperatureSet":21,"fanSpeed":0,"fanAutoMode":0,"airSwingLR":2,"airSwingUD":2,"ecoFunctionData":0,"ecoMode":0,"ecoNavi":0,"nanoe":2,"iAuto":0,"airDirection":0,"lastSettingMode":0},"deviceModuleNumber":"CS-Z35ZKEW","deviceHashGuid":"5071d4ca2b6cfd9792c3b62c46f96cc50bda1ab3035862cba23dd8095b5431cb","modelVersion":2,"coordinableFlg":true,"pairedFlg":false}]}]}
2024-07-02 15:20:47.124 INFO (MainThread) [custom_components.panasonic_cc] Got 1 devices
2024-07-02 15:20:47.642 ERROR (MainThread) [custom_components.panasonic_cc.pcomfortcloud.helpers] Error in get_device
Expected status code '200' but received '500'
Response body: {"code":5005,"message":"Adapter Communication error"}
2024-07-02 15:20:47.643 WARNING (MainThread) [custom_components.panasonic_cc.panasonic] Error updating device 5071d4ca2b6cfd9792c3b62c46f96cc50bda1ab3035862cba23dd8095b5431cb
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/panasonic.py", line 86, in do_update
    data = await self._api.get_device(self.id)`

**Comment by heldchen** [comment]
@asatron1 is your HVAC still working in the panasonic app? `"Adapter Communication error"` seems to indicate a hardware error...

**Comment by asatron1** [comment]
@heldchen 
yes, everything works with the APP.
Shortly before the update everything worked fine. The problem occurred immediately after the update

**Comment by heldchen** [comment]
I think @sockless-coding will have to add some debug logging to `get_device` so that we can see the request made - I suspect there's a regression in the device handling since the zone implementation (I did not yet update my installation from 1.0.48 as it still works fine for me).

**Comment by asatron1** [comment]
@heldchen 
After your question, I got the idea to unplug the air conditioner from the energy. After that, everything worked again.

@Csejka 
Is that also the solution for you?

![image](https://github.com/sockless-coding/panasonic_cc/assets/129151323/99077a1c-721f-44fc-9d0b-6aa31bfb76f9)

**Comment by sockless-coding** [comment]
@Csejka create a new Panasonic user and grant it access to your HVAC, then try using that user in HA. Panasonic isn't returning any information for your user.

**Comment by Csejka** [comment]
hi there 

i reseted the air cons and then connected both to the main user and then to the second user - now it works

best beni

**Comment by RonnieRocket2** [comment]
> Hi, after update from 1.0.56 to 1.0.58. i have the same problem. rename the groupname in the app and a reboot changes nothing
> 
> ![image](https://private-user-images.githubusercontent.com/129151323/345047547-0643fa5d-4ca8-41aa-abe3-f71ba6ef6c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTM2NDksIm5iZiI6MTcyMjk1MzM0OSwicGF0aCI6Ii8xMjkxNTEzMjMvMzQ1MDQ3NTQ3LTA2NDNmYTVkLTRjYTgtNDFhYS1hYmUzLWY3MWJhNmVmNmMyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNDA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDA1NjhhNzA0MjZhYzZlMTRhN2Q2Y2JlODBlMzc3MzBjMTQzOGQ3ZTYyNTQ0NGI3YzY5YzNjODk2ZDU2Yjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VAwbEhE33zFOy5ihelFlLMPqWm_45os_kZaef7Q1KxY)
> 
> Deleting and reconnecting doesn't change anything

I have the same issue

**Comment by Segran** [comment]
Same here, none of the advices above makes the least difference. Comfort Cloud have never been a marvel of reliability, but now it’s simply just silly - it does not work.

**Comment by sockless-coding** [comment]
@Segran if it has been working before, please enable debug logging and reload the integration and give me the logs, and I'll take a look. Though the Panasonic servers have had their fair share of issues lately...

**Comment by Segran** [comment]
Sure, have debugging enabled - but where the heck is the log-file? Have 2MFA and a working account with Panasonic Cloud, their app works just fine. 

I guess Panansonic - just as Audi Connect and Husqvarna - don’t approve of HA accessing their API...

**Comment by sockless-coding** [comment]
@Segran under System / Logs there's a Load Full Logs button it will show you the whole log. 
Easiest is you reload the integration and then head over to the logs, the last entries few entries containing `custom_components.panasonic_cc` is the only thing I need.

**Comment by sockless-coding** [comment]
I think the App hides the 5005 error and presents cached data until it gets a correct response.
Though that error you included was listed once and was triggered at 01:09... 
that also indicates that there is at least one Panasonic device registered in HA.

**Comment by Segran** [comment]
Yes, the device is registered but it doesn’t give any entities. That’s my problem…..Skickat från min iPad20 sep. 2024 kl. 19:57 skrev Jimmy Everling ***@***.***>:﻿
I think the App hides the 5005 error and presents cached data until it gets a correct response.
Though that error you included was listed once and was triggered at 01:09...
that also indicates that there is at least one Panasonic device registered in HA.

**Comment by Segran** [comment]
Bilagan tillgänglig fram till 20 okt. 2024
Klicka för att hämta
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAcLgrj1ZfD6IacZMcYJm4sBL21zOAZA50lzoX9E4GteOcbEH-7vQZZ-Z%2F%24%7Bf%7D%3Fo%3DAmEwgKL4RTdI45GTsIS8wO-wPXkniAqaqsD9Ypf-jTlE%26v%3D1%26x%3D3%26a%3DCAogcIgxV97zwzDEfGqtjmC5MLgBj-v23sjeDOdxUKvxHV4SdhDO8KaKoTIYzoCi3qoyIgEAKgkC6AMA_xAIPhhSBEvbXM5aBNBln5lqJey5K-PTr0pge8ej51QPxDzKmOBq-vg2NJvowHy6f1BkUwlXQGRyJX6u_4ov3oQQiQmsaNv4PDcmpNroyltv0cKRL4bb8JCZ_-DKggE%26e%3D1729458896%26fl%3D%26r%3D80A7CF95-27EA-48A0-89EB-01EBD60895C2-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DF04192C7-B4C7-4F0D-BFE0-375218F96287%26p%3D161%26s%3DnjF1OMkL0GIUWKMUa3GLRONeTWM&uk=i2M0cy9_gQG1kDNGun9YCA&f=home-assistant_2024-09-20T21-08-10.677Z.log&sz=42005848>home-assistant_2024-09-20T21-08-10.677Z.log
42 MB

**Comment by sockless-coding** [comment]
@Segran What heat pump do you have? 
The API reports device type 1 (My CS-HZ25UKE reports as type 3) and the deviceHashGuid is not included, so they might have changed how that should be computed.

**Comment by sockless-coding** [comment]
@Segran give 2024.9.0 a try

**Comment by Segran** [comment]
I hase a CZ-CS35TKE and CS-TACG1 Wifi adapter.
2024.9.0 made a heck of a difference! I now have a bunch of entities that I have never seen before!

Thanks!

**Comment by Segran** [comment]
For some obscure reason I'm listed as "owner" of this sw. maybe you can correct that as well?

**Comment by sockless-coding** [comment]
@Segran what do you mean listed as "owner"?

**Comment by Segran** [comment]
I got an automated (?) mail from GitHub after I issued a question that asked me ”to have a look at the issue since you are the code owner”.Skickat från min iPad24 sep. 2024 kl. 07:19 skrev Jimmy Everling ***@***.***>:﻿
@Segran what do you mean listed as "owner"?

**Comment by sockless-coding** [comment]
Might have been because I referenced this issue in another one...

**Comment by KrzysztofMaciejewski** [comment]
Hi 

Latest version installed and "No devices" problem showed up

logs:

`
2024-11-09 13:10:47.948 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Found 2 unknown device(s):
{"deviceGuid": "B835711822", "deviceType": "2", "deviceName": "Skawi\u0144ska ", "connectionStatus": 1, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 0, "temperature": -3}, {"zoneId": 2}], "tankStatus": {"operationStatus": 0, "temperature": 45}}
 {"deviceGuid": "B194694239", "deviceType": "2", "deviceName": "S31", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 45}}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
2024-11-09 13:10:48.170 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Failed to get aquarea device info for B835711822
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-11-09 13:10:48.306 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Failed to get aquarea device info for B194694239
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'`

Any suggestion what is the problem and how to fix it?
Thanks

**Comment by TetraLama** [comment]
Hey there.

Firstly, thanks for this integration. I used it some times ago.

I'm deploying a new HA, and want to integrate my HeatPump, but I got the `No devices` error.

Here is the debug log:
```python
{"deviceGuid": "B736809204", "deviceType": "2", "deviceName": "PAC  MJ", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 50}}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310

2024-11-11 10:50:18.979 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Failed to get aquarea device info for B736809204
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
``` 

Do you have any ideas why ?
Kindly
