### ISSUE TITLE
eco_navi NoneType

### ISSUE THREAD

**Issue by codyc1515** [sockless-coding/panasonic_cc#236]
I am working on a fix.

```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:364
integration: Switch (documentation, issues)
First occurred: 06:54:59 (4 occurrences)
Last logged: 07:34:13

Error while setting up panasonic_cc platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/panasonic_cc/switch.py", line 30, in async_setup_entry
    if device.support_eco_navi:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/panasonic.py", line 274, in support_eco_navi
    return self._details.features.eco_navi
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'features'
```

**Comment by sockless-coding** [comment]
I have some bug fixes I haven't checked in yet
