### ISSUE TITLE
ValueError: 2 is not a valid EcoNaviMode

### ISSUE THREAD

**Issue by codyc1515** [sockless-coding/panasonic_cc#237]
I’m unable to set ECONAVI from HA. When I set it, after a few seconds it reverts back to off. The value of 2 seems to come from when I set it in the app. I am on the very latest version of both.

```


This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.panasonicdevice
Source: custom_components/panasonic_cc/pcomfortcloud/panasonicdevice.py:12
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 08:47:27 (1 occurrences)
Last logged: 08:47:27

Error reading property 'ecoNavi' with value '2'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicdevice.py", line 12, in read_enum
    return type(json[key])
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 2 is not a valid EcoNaviMode

```

**Comment by sockless-coding** [comment]
Hmm, is EcoNavi a simple toggle switch in the app or does it have some sort of mode select?
Or is 0 N/A, 1 Off and 2 On
I don't have it on my device

**Comment by codyc1515** [comment]
Yes, it’s Unavailable, Off & On.
