### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by blokboiiii** [sockless-coding/panasonic_cc#246]
Came home this arvo and noticed that the integration wasnt working. Ran for the latest update and restarted, still to no avail.

Checked logs, seen the below

Deleted devices, deleted integration and re loaded, and now all i get is "unexpected error creating device"

Any idea what ive done to break it?

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 5:29:20 PM (7 occurrences)
Last logged: 5:38:47 PM

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 50, in start_session
    await self._get_groups()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 61, in _get_groups
    self._groups = await self.execute_get(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 131, in execute_get
    check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 25, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_groups: Expected status code 200, received: 401: <bound method ClientResponse.text of <ClientResponse(https://accsmart.panasonic.com/device/group) [401 Unauthorized]>
<CIMultiDictProxy('Server': 'CloudFront', 'Date': 'Mon, 01 Jul 2024 07:29:18 GMT', 'Content-Length': '67', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 c4f944071d931af43f56c1d59df3d890.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MEL52-P2', 'Alt-Svc': 'h3=":443"; ma=86400', 'X-Amz-Cf-Id': '~~~', 'X-XSS-Protection': '1; report=1;mode=block', 'X-Frame-Options': 'DENY', 'Content-Security-Policy': "script-src 'self' 'unsafe-inline'", 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains')>
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 80, in async_setup_entry
    await api.start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 53, in start_session
    await self.reauthenticate()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 71, in reauthenticate
    await self._authentication.authenticate(self._username, self._password)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 75, in authenticate
    await self._retrieve_client_acc()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 258, in _retrieve_client_acc
    await check_response(response, 'get_acc_client_id', 200)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 30, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_acc_client_id: Expected status code 200, received: 401: {
  "code":4106,
  "message":"New version app has been published"
}
```

**Comment by blokboiiii** [comment]
I missed that I wasnt on the newest HA core, updated that and it worked. AKA im an idiort :)
