### ISSUE TITLE
panasonic heat pump integration issues

### ISSUE THREAD

**Issue by akwiatkowski** [sockless-coding/panasonic_cc#256]
Hello.

I've added integration to HA. Used correct credentials - the same I signed on mobile app and website. I don't know about 2FA and doesn't have it enabled. On mobile app I cannot add more users, and I cannot change important account settings.

I don't see any measurements from heat pump - inside temperature: unavailable.

Firmware: 1.21.1

```
Logger: custom_components.panasonic_cc.pcomfortcloud.helpers
Source: custom_components/panasonic_cc/pcomfortcloud/helpers.py:27
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 16:08:56 (1 occurrences)
Last logged: 16:08:56
Error in get_device Expected status code '200' but received '403' Response body: {"code":4300,"message":"Have no authority to the request"}
```

```
Logger: custom_components.panasonic_cc.panasonic
Source: custom_components/panasonic_cc/panasonic.py:86
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 16:08:56 (1 occurrences)
Last logged: 16:08:56
Error updating device 5725edf3494187174b34676dc837b41b

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/panasonic.py", line 86, in do_update
    data = await self._api.get_device(self.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 123, in get_device
    json_response = await self.execute_get(self._get_device_status_url(device_guid), "get_device", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 140, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_device: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}
```

```
ogger: custom_components.panasonic_cc.pcomfortcloud.helpers
Source: custom_components/panasonic_cc/pcomfortcloud/helpers.py:20
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 16:08:57 (1 occurrences)
Last logged: 16:08:57
Error in history Expected status code '200' but received '403' Payload: {'deviceGuid': 'B433623312', 'dataMode': 2, 'date': '20240723', 'osTimezone': '+02:00'} Response body: {"code":4300,"message":"Have no authority to the request"}
```

```
Logger: custom_components.panasonic_cc
Source: custom_components/panasonic_cc/__init__.py:92
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 16:08:57 (1 occurrences)
Last logged: 16:08:57
Failed to setup device: <CORRECT NAME> (str.format() argument after ** must be a mapping, not PanasonicDeviceInfo)
```

**Comment by sockless-coding** [comment]
@akwiatkowski Hi, the error message indicates an access problem (Have no authority to the request).
If you enable debug or info log, look for an entry that looks like `[custom_components.panasonic_cc] Got X devices` where `X` is the number of devices found, does it say something other than 1? Have you had other devices linked to the account?

I would recommend that you create a new account that home assistant can use, using the same account in both the APP and HA can cause issues.

**Comment by akwiatkowski** [comment]
Hello. I'm not sure how I did but had working if for a 1-2 months. Today after upgrading it stopped working. I have latest version, created new account which has full access to heat pump. Today when I want to add integration it get empty list of heat pumps.

![image](https://github.com/user-attachments/assets/ed6246e2-0546-41c6-a7bb-2ac611f5ac5d)

I'm not home assistant expert and I didn't find anything in logs.

**Comment by sockless-coding** [comment]
@akwiatkowski if you get the no devices, the Panasonic Api doesn't return anything to HA. Do you see the devices if you used those credentials in the App?

**Comment by sockless-coding** [comment]
@stevocz can you provide some debug logs (See https://github.com/sockless-coding/panasonic_cc/issues/234#issuecomment-2364292396 if you don't know how)

**Comment by sockless-coding** [comment]
@stevocz I've done some changes to the device status call in 2024.9.0

**Comment by stevocz** [comment]
hi. today i updated your app but nothing change.

I cannot set debug log because i cannot add integration without device (or i don't know how). And when i set correct ID and password always write "no devices"

My HA is on synology as container

**Comment by sockless-coding** [comment]
@stevocz what heat pump do you have?
You can enable debug logging in the configuration.yaml by adding the following:
```yaml
logger:
  default: info
  logs:
    custom_components.panasonic_cc: debug
```

**Comment by stevocz** [comment]
i have WH-SDC09H3E8+WH-UD09HE8

i try add to config when i come home

**Comment by sockless-coding** [comment]
@stevocz update to 2024.9.1 it has some additional logs that I need before I can add Aquarea device support https://github.com/sockless-coding/panasonic_cc/issues/310

**Comment by stevocz** [comment]
after update to 2024.9.1 it write Unexpected error creating device. 

in log is correctly shown my heat pump.
i am changed deviceGuid to XXXXXXXXXX. in original is real deviceID from CZ-TAW1B


`2024-09-24 00:43:36.192 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Starting Session
2024-09-24 00:43:36.212 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Loaded settings from '/root/.panasonic-settings'
2024-09-24 00:43:36.214 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Access token is valid
2024-09-24 00:43:37.503 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: {"a2wStatus":{"statusCode":200},"uiFlg":false,"groupCount":1,"groupList":[{"groupId":1552406,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"XXXXXXXXXX","deviceType":"2","deviceName":"Doma","connectionStatus":0,"operationMode":1,"zoneStatus":[{"zoneId":1,"operationStatus":0,"temperature":0},{"zoneId":2}],"tankStatus":{"operationStatus":1,"temperature":50}}]}]}`

**Comment by sockless-coding** [comment]
@stevocz you didn't get any other errors / warnings in the log?

**Comment by stevocz** [comment]
only this but it is not in full file log

Logger: custom_components.panasonic_cc.config_flow
Zdroj: custom_components/panasonic_cc/config_flow.py:73
Integrácia: panasonic_cc (dokumentácia, problémy)
Prvýkrát sa vyskytol: 00:43:37 (1 výskytov)
Naposledy prihlásený: 00:43:37

Bad logger message: Unexpected error creating device ((TypeError('sequence item 0: expected str instance, dict found'),))

**Comment by sockless-coding** [comment]
@stevocz yeah the Aquarea logging was broken but should be fixed in 2024.9.2

**Comment by stevocz** [comment]
new log

```
2024-09-24 11:43:07.037 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Starting Session
2024-09-24 11:43:07.065 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Loaded settings from '/root/.panasonic-settings'
2024-09-24 11:43:07.067 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Access token is valid
2024-09-24 11:43:07.748 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: {"a2wStatus":{"statusCode":200},"uiFlg":false,"groupCount":1,"groupList":[{"groupId":1552406,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"B123456789","deviceType":"2","deviceName":"Doma","connectionStatus":0,"operationMode":1,"zoneStatus":[{"zoneId":1,"operationStatus":0,"temperature":0},{"zoneId":2}],"tankStatus":{"operationStatus":1,"temperature":50}}]}]}
2024-09-24 11:43:07.748 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Found 1 unknown device(s):
{"deviceGuid": "B123456789", "deviceType": "2", "deviceName": "Doma", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 0, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 50}}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
2024-09-24 11:43:10.526 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/a2wInfo/B123456789, response: {"result":0}
2024-09-24 11:43:10.526 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Got aquarea device info for: B123456789:
{"result": 0}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
2024-09-24 11:43:10.526 DEBUG (MainThread) [custom_components.panasonic_cc.config_flow] Not devices found
```

**Comment by sockless-coding** [comment]
Guess that wasn't the call to get the status of Aquarea devices...

**Comment by Tokop275** [comment]
Hallo,
I connected my device - heatpomp WH-MDC09J3E5.
Unfortunately only three entities are available. Is it possible to add additional parameters and control options? For example it would be very good to have information when the pump is defrosting.
![Screenshot_20250115-135328](https://github.com/user-attachments/assets/6f39359c-86e0-4628-97bf-7b08a66447d6)
