### ISSUE TITLE
Faild to setup - again:(

### ISSUE THREAD

**Issue by raczgy** [sockless-coding/panasonic_cc#257]
hi All,
I have received back  the issue again after updated the  HA core.
Now I have this HA setup:
Core  2024.7.3
Supervisor 2024.06.2
Operating System 11.3
Frontend 20240710.0
Panasonic addon: 1.0.58

Log entry for panasonic:
2024-07-26 10:01:53.033 ERROR (MainThread) [custom_components.panasonic_cc.pcomfortcloud.helpers] Error in get_token
Expected status code '200' but received '400'
Response body: {"error":"invalid_request","error_description":"Missing required parameter: code"}
2024-07-26 10:01:53.034 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 80, in async_setup_entry
    await api.start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 48, in start_session
    await super().start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 49, in start_session
    await self._authentication.authenticate(self._username, self._password)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 67, in authenticate
    await self._request_new_token(code, code_verifier)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 228, in _request_new_token
    await check_response(response, 'get_token', 200)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_token: Expected status code 200, received: 400: {"error":"invalid_request","error_description":"Missing required parameter: code"}

please let me know your thoughts.

Thanks,
Gyuri

**Comment by raczgy** [comment]
I did a restore back to core  6.4 but still no luck on this.
I already went through the MFA settings a month or so ago.
not sure what went wrong the error is very similar.

**Comment by sockless-coding** [comment]
@raczgy Hi, could you enable debug logging and provide some more logs. You seem to get an authentication response that isn't handled.

**Comment by raczgy** [comment]
2024-07-26 11:33:45.097 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Starting Session
2024-07-26 11:33:45.099 INFO (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Settings file '/root/.panasonic-settings' was not found
2024-07-26 11:33:45.099 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] No refresh token found
2024-07-26 11:33:45.100 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Requesting authorization, {"challenge": "ZUeDlK0pJyUE4Qk6vEZGkmtTGYq1M7ZJc2CxTpBBQYg", "state": "THvaGP6BXmXTeblc8fro"}
2024-07-26 11:33:45.517 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Authorization result, {"redirect": "/login?state=hKFo2SBhMThndTc0OUgtSnQ2ZFVTTElIaW4zVE5oQjRuQ2NiVqFupWxvZ2luo3RpZNkgT0JESlRFamRzcjdQM1ZsVUJEakdzY1oycm5WMUkzQmajY2lk2SBYbXk2eElZSWl0TXhuZ2pCMnJIdmxtNkhTRE5uYU1KeA&client=Xmy6xIYIitMxngjB2rHvlm6HSDNnaMJx&protocol=oauth2&scope=openid%20offline_access%20comfortcloud.control%20a2w.control&audience=https%3A%2F%2Fdigital.panasonic.com%2FXmy6xIYIitMxngjB2rHvlm6HSDNnaMJx%2Fapi%2Fv1%2F&response_type=code&code_challenge=ZUeDlK0pJyUE4Qk6vEZGkmtTGYq1M7ZJc2CxTpBBQYg&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsImVudiI6eyJhbmRyb2lkIjoiMzAifSwidmVyc2lvbiI6IjIuOS4zIn0%3D&redirect_uri=panasonic-iot-cfc%3A%2F%2Fauthglb.digital.panasonic.com%2Fandroid%2Fcom.panasonic.ACCsmart%2Fcallback", "response": "Found. Redirecting to /login?state=hKFo2SBhMThndTc0OUgtSnQ2ZFVTTElIaW4zVE5oQjRuQ2NiVqFupWxvZ2luo3RpZNkgT0JESlRFamRzcjdQM1ZsVUJEakdzY1oycm5WMUkzQmajY2lk2SBYbXk2eElZSWl0TXhuZ2pCMnJIdmxtNkhTRE5uYU1KeA&client=Xmy6xIYIitMxngjB2rHvlm6HSDNnaMJx&protocol=oauth2&scope=openid%20offline_access%20comfortcloud.control%20a2w.control&audience=https%3A%2F%2Fdigital.panasonic.com%2FXmy6xIYIitMxngjB2rHvlm6HSDNnaMJx%2Fapi%2Fv1%2F&response_type=code&code_challenge=ZUeDlK0pJyUE4Qk6vEZGkmtTGYq1M7ZJc2CxTpBBQYg&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsImVudiI6eyJhbmRyb2lkIjoiMzAifSwidmVyc2lvbiI6IjIuOS4zIn0%3D&redirect_uri=panasonic-iot-cfc%3A%2F%2Fauthglb.digital.panasonic.com%2Fandroid%2Fcom.panasonic.ACCsmart%2Fcallback"}
2024-07-26 11:33:45.517 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Following authorization redirect, {"url": "https://authglb.digital.panasonic.com//login?state=hKFo2SBhMThndTc0OUgtSnQ2ZFVTTElIaW4zVE5oQjRuQ2NiVqFupWxvZ2luo3RpZNkgT0JESlRFamRzcjdQM1ZsVUJEakdzY1oycm5WMUkzQmajY2lk2SBYbXk2eElZSWl0TXhuZ2pCMnJIdmxtNkhTRE5uYU1KeA&client=Xmy6xIYIitMxngjB2rHvlm6HSDNnaMJx&protocol=oauth2&scope=openid%20offline_access%20comfortcloud.control%20a2w.control&audience=https%3A%2F%2Fdigital.panasonic.com%2FXmy6xIYIitMxngjB2rHvlm6HSDNnaMJx%2Fapi%2Fv1%2F&response_type=code&code_challenge=ZUeDlK0pJyUE4Qk6vEZGkmtTGYq1M7ZJc2CxTpBBQYg&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsImVudiI6eyJhbmRyb2lkIjoiMzAifSwidmVyc2lvbiI6IjIuOS4zIn0%3D&redirect_uri=panasonic-iot-cfc%3A%2F%2Fauthglb.digital.panasonic.com%2Fandroid%2Fcom.panasonic.ACCsmart%2Fcallback", "state": "hKFo2SBhMThndTc0OUgtSnQ2ZFVTTElIaW4zVE5oQjRuQ2NiVqFupWxvZ2luo3RpZNkgT0JESlRFamRzcjdQM1ZsVUJEakdzY1oycm5WMUkzQmajY2lk2SBYbXk2eElZSWl0TXhuZ2pCMnJIdmxtNkhTRE5uYU1KeA"}
2024-07-26 11:33:45.856 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Authorization redirect response, {"headers": {"Date": "Fri, 26 Jul 2024 09:33:45 GMT", "Content-Type": "text/html; charset=utf-8", "Transfer-Encoding": "chunked", "Connection": "keep-alive", "CF-Ray": "8a9363d7aa495af4-VIE", "CF-Cache-Status": "DYNAMIC", "Cache-Control": "no-store, max-age=0, no-transform", "Etag": "W/\"e989-c9J7bWY5RPlVDlMwfjDhJ7Fr5mo\"", "Set-Cookie": "_csrf=KZWJduZOeocXJBjGf9zwI-Dk; Max-Age=864000; Path=/usernamepassword/login; HttpOnly; Secure", "Strict-Transport-Security": "max-age=31536000; includeSubDomains", "Vary": "Accept-Encoding", "Content-Security-Policy": "frame-ancestors 'none'", "Pragma": "no-cache", "Referrer-Policy": "same-origin", "X-Auth0-RequestId": "9d7b4787eecb0665324d", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "deny", "X-RateLimit-Limit": "1500", "X-RateLimit-Remaining": "1499", "X-RateLimit-Reset": "1721986426", "X-Robots-Tag": "noindex, nofollow", "X-XSS-Protection": "1; mode=block", "alt-svc": "h3=\":443\"; ma=86400", "x-azure-ref": "20240726T093345Z-16dcb67469b429wqvp1avhh3dn0000000n0g00000000t1he", "X-Cache": "CONFIG_NOCACHE"}, "cookies": "Set-Cookie: _csrf=KZWJduZOeocXJBjGf9zwI-Dk; Domain=authglb.digital.panasonic.com; HttpOnly; Max-Age=864000; Path=/usernamepassword/login; Secure"}
2024-07-26 11:33:45.856 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Authenticating with username and password, {"csrf": {"expires": "", "path": "/usernamepassword/login", "comment": "", "domain": "authglb.digital.panasonic.com", "max-age": "864000", "secure": true, "httponly": true, "version": "", "samesite": ""}, "state": "hKFo2SBhMThndTc0OUgtSnQ2ZFVTTElIaW4zVE5oQjRuQ2NiVqFupWxvZ2luo3RpZNkgT0JESlRFamRzcjdQM1ZsVUJEakdzY1oycm5WMUkzQmajY2lk2SBYbXk2eElZSWl0TXhuZ2pCMnJIdmxtNkhTRE5uYU1KeA"}
2024-07-26 11:33:46.362 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Authentication response, {"html": "<form method=\"post\" name=\"hiddenform\" action=\"https://authglb.digital.panasonic.com/login/callback\">\n    <input type=\"hidden\" name=\"wa\" value=\"wsignin1.0\">\n    <input type=\"hidden\" \n           name=\"wresult\" \n           value=\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiYjhlNGEzMmM1YTRjY2RlMmQ4OTQ0NTRiNmYxZjg2ZjdmMDUxMzE4OWE0OGVkNDQxOWI5Zjc4MThmMmQwM2U4OCIsImVtYWlsIjoicmd5b3JneTc0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJzaWQiOiJWVlp0Vk9yVDJCUXNybm5md2VxV1AtOGViZFZrSk9UbCIsImlhdCI6MTcyMTk4NjQyNiwiZXhwIjoxNzIxOTg2NDg2LCJhdWQiOiJ1cm46YXV0aDA6cGRwYXV0aGdsYi1hMTpQYW5hc29uaWNJRC1BdXRoZW50aWNhdGlvbiIsImlzcyI6InVybjphdXRoMCJ9.WdR6BJD6D1BApvvUpCVMF-066OjNysT-o5KvPaf2MsEx8T2mbKlM_cXagh1DzOAZEML_3w1sIsCEhD-_GZHoXEZv6fYWZUhtPG0f_7tnM2WlGBwxGFSPsoCuaACIx0U4vv4FAWcf6as-pfwDaGvZigZu86kwM_09drt1IXK8NPdHsoiq-UKI6fUFy_OQIcaHcBduP658gkn46hiiNV-9jnv5MqNulbIPjUbycLhmnKrIJBd9GIE46OwfuYYm8cV6vwN8P-5N_YeCoG4Ha3o7tcr6czIVgSFUn8RTxuPCoLVpBWIoVwmovwD-qloIBU2o6srmqPRIspovc7KV1dY7mw\">\n    <input type=\"hidden\" name=\"wctx\" value=\"{&#34;strategy&#34;:&#34;auth0&#34;,&#34;auth0Client&#34;:&#34;eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsImVudiI6eyJhbmRyb2lkIjoiMzAifSwidmVyc2lvbiI6IjIuOS4zIn0=&#34;,&#34;tenant&#34;:&#34;pdpauthglb-a1&#34;,&#34;connection&#34;:&#34;PanasonicID-Authentication&#34;,&#34;client_id&#34;:&#34;Xmy6xIYIitMxngjB2rHvlm6HSDNnaMJx&#34;,&#34;response_type&#34;:&#34;code&#34;,&#34;scope&#34;:&#34;openid offline_access comfortcloud.control a2w.control&#34;,&#34;redirect_uri&#34;:&#34;panasonic-iot-cfc://authglb.digital.panasonic.com/android/com.panasonic.ACCsmart/callback&#34;,&#34;state&#34;:&#34;hKFo2SBhMThndTc0OUgtSnQ2ZFVTTElIaW4zVE5oQjRuQ2NiVqFupWxvZ2luo3RpZNkgT0JESlRFamRzcjdQM1ZsVUJEakdzY1oycm5WMUkzQmajY2lk2SBYbXk2eElZSWl0TXhuZ2pCMnJIdmxtNkhTRE5uYU1KeA&#34;,&#34;sid&#34;:&#34;VVZtVOrT2BQsrnnfweqWP-8ebdVkJOTl&#34;,&#34;audience&#34;:&#34;https://digital.panasonic.com/Xmy6xIYIitMxngjB2rHvlm6HSDNnaMJx/api/v1/&#34;,&#34;realm&#34;:&#34;PanasonicID-Authentication&#34;}\">\n    <noscript>\n        <p>\n            Script is disabled. Click Submit to continue.\n        </p><input type=\"submit\" value=\"Submit\">\n    </noscript>\n</form>"}
2024-07-26 11:33:46.365 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Callback with parameters, {"wa": "wsignin1.0", "wresult": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiYjhlNGEzMmM1YTRjY2RlMmQ4OTQ0NTRiNmYxZjg2ZjdmMDUxMzE4OWE0OGVkNDQxOWI5Zjc4MThmMmQwM2U4OCIsImVtYWlsIjoicmd5b3JneTc0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJzaWQiOiJWVlp0Vk9yVDJCUXNybm5md2VxV1AtOGViZFZrSk9UbCIsImlhdCI6MTcyMTk4NjQyNiwiZXhwIjoxNzIxOTg2NDg2LCJhdWQiOiJ1cm46YXV0aDA6cGRwYXV0aGdsYi1hMTpQYW5hc29uaWNJRC1BdXRoZW50aWNhdGlvbiIsImlzcyI6InVybjphdXRoMCJ9.WdR6BJD6D1BApvvUpCVMF-066OjNysT-o5KvPaf2MsEx8T2mbKlM_cXagh1DzOAZEML_3w1sIsCEhD-_GZHoXEZv6fYWZUhtPG0f_7tnM2WlGBwxGFSPsoCuaACIx0U4vv4FAWcf6as-pfwDaGvZigZu86kwM_09drt1IXK8NPdHsoiq-UKI6fUFy_OQIcaHcBduP658gkn46hiiNV-9jnv5MqNulbIPjUbycLhmnKrIJBd9GIE46OwfuYYm8cV6vwN8P-5N_YeCoG4Ha3o7tcr6czIVgSFUn8RTxuPCoLVpBWIoVwmovwD-qloIBU2o6srmqPRIspovc7KV1dY7mw", "wctx": "{\"strategy\":\"auth0\",\"auth0Client\":\"eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsImVudiI6eyJhbmRyb2lkIjoiMzAifSwidmVyc2lvbiI6IjIuOS4zIn0=\",\"tenant\":\"pdpauthglb-a1\",\"connection\":\"PanasonicID-Authentication\",\"client_id\":\"Xmy6xIYIitMxngjB2rHvlm6HSDNnaMJx\",\"response_type\":\"code\",\"scope\":\"openid offline_access comfortcloud.control a2w.control\",\"redirect_uri\":\"panasonic-iot-cfc://authglb.digital.panasonic.com/android/com.panasonic.ACCsmart/callback\",\"state\":\"hKFo2SBhMThndTc0OUgtSnQ2ZFVTTElIaW4zVE5oQjRuQ2NiVqFupWxvZ2luo3RpZNkgT0JESlRFamRzcjdQM1ZsVUJEakdzY1oycm5WMUkzQmajY2lk2SBYbXk2eElZSWl0TXhuZ2pCMnJIdmxtNkhTRE5uYU1KeA\",\"sid\":\"VVZtVOrT2BQsrnnfweqWP-8ebdVkJOTl\",\"audience\":\"https://digital.panasonic.com/Xmy6xIYIitMxngjB2rHvlm6HSDNnaMJx/api/v1/\",\"realm\":\"PanasonicID-Authentication\"}"}
2024-07-26 11:33:46.783 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Callback response, {"redirect": "/authorize/resume?state=OBDJTEjdsr7P3VlUBDjGscZ2rnV1I3Bf", "html": "Found. Redirecting to /authorize/resume?state=OBDJTEjdsr7P3VlUBDjGscZ2rnV1I3Bf"}
2024-07-26 11:33:47.399 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Callback redirect, {"redirect": "/mf?state=hKFo2SA0OGsxYzl2NEozN2g4aGt3Sl9fMjMtcGpKLVAzQjRzU6Fuo21mYaN0aWTZIE9CREpURWpkc3I3UDNWbFVCRGpHc2NaMnJuVjFJM0Jmo2NpZNkgWG15NnhJWUlpdE14bmdqQjJySHZsbTZIU0RObmFNSng", "html": "Found. Redirecting to /mf?state=hKFo2SA0OGsxYzl2NEozN2g4aGt3Sl9fMjMtcGpKLVAzQjRzU6Fuo21mYaN0aWTZIE9CREpURWpkc3I3UDNWbFVCRGpHc2NaMnJuVjFJM0Jmo2NpZNkgWG15NnhJWUlpdE14bmdqQjJySHZsbTZIU0RObmFNSng"}
2024-07-26 11:33:47.399 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Requesting a new token
2024-07-26 11:33:47.742 ERROR (MainThread) [custom_components.panasonic_cc.pcomfortcloud.helpers] Error in get_token
Expected status code '200' but received '400'
Response body: {"error":"invalid_request","error_description":"Missing required parameter: code"}
2024-07-26 11:33:47.742 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 80, in async_setup_entry
    await api.start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 48, in start_session
    await super().start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 49, in start_session
    await self._authentication.authenticate(self._username, self._password)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 67, in authenticate
    await self._request_new_token(code, code_verifier)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 228, in _request_new_token
    await check_response(response, 'get_token', 200)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_token: Expected status code 200, received: 400: {"error":"invalid_request","error_description":"Missing required paramete

**Comment by sockless-coding** [comment]
You are being redirected to the multifactor setup page... did you set up the multifactor? If you did, did you set it to SMS or TOTP?

**Comment by raczgy** [comment]
I did it a month ago with SMS. I logged out and in from my iphone to the compfort app but there was no issue with it.
I'll try again

**Comment by raczgy** [comment]
ok, so I did a reset on my multifactor auth. than logged out and in from the mobile app.
Restarted HA. Still no luck.
than I  tried to add hub that failed with an unknown error.
Reloaded addon
and now it works.

not sure why. It seems we may need to do some magic every now and then.
I close this case as it seems to be the exactly the same as previously.
