### ISSUE TITLE
Error fetching device data from API: (get_device: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}

### ISSUE THREAD

**Issue by maurilloh** [sockless-coding/panasonic_cc#273]
After upgrade from version 1.0.58 i have this issue, some one could help me? thanks.

**Comment by AndreaMagis** [comment]
Me too...

**Comment by ddemarch** [comment]
I also have the same problem following the update to version 1.1.16. I can’t downgrade to version 1.0.58, which was working fine before. It is not available in HACS. Thank you very much.

**Comment by mtanasiewicz** [comment]
Same here
<img width="752" alt="image" src="https://github.com/user-attachments/assets/5df2cf86-58ac-4c64-9e5d-9bdc0a10a3ca">

**Comment by sockless-coding** [comment]
Hello, can you please provide some more detailed logs. 
That message just says that you do not have any permissions to access the device.

**Comment by mtanasiewicz** [comment]
Is this what you are looking for, or should I search elsewhere?

This error originated from a custom integration.

Logger: custom_components.panasonic_cc.coordinator
Source: custom_components/panasonic_cc/coordinator.py:77
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 3:42:39 PM (175 occurrences)
Last logged: 7:50:59 PM

Error fetching device data from API: (get_device: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 77, in _fetch_device_data
    self._device = await self._api_client.get_device(self._panasonic_device_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 121, in get_device
    json_response = await self.execute_get(self._get_device_status_url(device_info.guid), "get_device", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 144, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_device: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}

**Comment by sockless-coding** [comment]
I would need the group/setup requests you need to activate debug logging for the integration to see in the log it should look like this:
```
2024-08-08 11:46:04.914 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: {"uiFlg":false,"groupCount":1,"groupList":[{"groupId":<REDACTED>,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"CS-HZ25UKE+<REDACTED>","deviceType":"3","deviceName":"Living Room","permission":2,"temperatureUnit":0,"summerHouse":2,"nanoeStandAlone":true,"autoMode":true,"modeAvlList":{"autoMode":1},"parameters":{"operate":0,"operationMode":2,"temperatureSet":20,"fanSpeed":3,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":3,"ecoFunctionData":0,"ecoMode":0,"ecoNavi":0,"nanoe":1,"iAuto":0,"airDirection":0,"lastSettingMode":0},"deviceModuleNumber":"CS-HZ25UKE","deviceHashGuid":<REDACTED>,"modelVersion":1,"coordinableFlg":false}]}]}
2024-08-08 11:46:04.914 INFO (MainThread) [custom_components.panasonic_cc] Got 1 devices
2024-08-08 11:46:06.411 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/CS-HZ25UKE%2B<REDACTED>, response: {"timestamp":1723110366241,"permission":2,"summerHouse":2,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":true,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":0,"operationMode":2,"temperatureSet":20,"fanSpeed":3,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":3,"ecoMode":0,"ecoNavi":0,"nanoe":1,"iAuto":0,"airDirection":0,"insideTemperature":21,"outTemperature":18,"airQuality":0},"deviceNanoe":1}
```

**Comment by mtanasiewicz** [comment]
How do I activate debug logging? Could you navigate me a bit?

**Comment by sockless-coding** [comment]
If the integration is listed under Devices, you can just click the "enable debug logging" 
![image](https://github.com/user-attachments/assets/463e4387-1b8b-4b16-ac99-0a1556a122be)

If It's not there, you can edit your configuration.yaml
```yaml
logger:
  default: info
  logs:
    custom_components.panasonic_cc: debug
```
The logger section might not be there so you have to add it.

**Comment by mtanasiewicz** [comment]
Here is the log file

[home-assistant_2024-08-08T18-47-49.699Z.log](https://github.com/user-attachments/files/16552236/home-assistant_2024-08-08T18-47-49.699Z.log)

**Comment by sockless-coding** [comment]
@mtanasiewicz it's your `Tobołowo` device breaking everything... it doesn't look like a HVAC what type of device is it?
I can probably add some checks so it doesn't try to access non HVACs

**Comment by mtanasiewicz** [comment]
We have couple of air conditioning devices, and there is one that is unknown type. However previous integration worked perfectly. If you could fix it, it would be perfect :)

**Comment by mtanasiewicz** [comment]
I think that handling of the 403 status by skipping the device would also be a viable choice. All other devices should work.

**Comment by sockless-coding** [comment]
Well, the previous version probably threw a few errors but since the strange device was the last one the other ones got added...
I've added some checks in v1.1.7 give it a try

**Comment by mtanasiewicz** [comment]
1.1.7 fixed it, thanks!

**Comment by sockless-coding** [comment]
Hopefully it fixes it for the others as well.
@mtanasiewicz that strange device looks like it could be a water heater since it has a tank status with a temp reading of 50C and some modes... does it show up in the CFC app?

**Comment by maurilloh** [comment]
I've upgraded to the 1.1.7 but now it can't find any devices.
![image](https://github.com/user-attachments/assets/4a831dc3-1c0f-4200-b722-9713c6a5153c)

**Comment by sockless-coding** [comment]
@maurilloh I need some more info, please provide some debug logs.

**Comment by maurilloh** [comment]
after the message the integration is not loaded. I don't have any logs

**Comment by sockless-coding** [comment]
@maurilloh you need to go to the logs page https://my.home-assistant.io/redirect/logs/ and click load full logs

**Comment by mgeeky** [comment]
@sockless-coding Since I'm also affected by this very error, please find below an excerpt from my logs:

```
2024-08-09 00:54:44.258 INFO (MainThread) [custom_components.panasonic_cc] Got 6 devices
2024-08-09 00:54:45.265 ERROR (MainThread) [custom_components.panasonic_cc.pcomfortcloud.helpers] Error in get_device
Expected status code '200' but received '403'
Response body: {"code":4300,"message":"Have no authority to the request"}
2024-08-09 00:54:45.266 ERROR (MainThread) [custom_components.panasonic_cc.coordinator] Error fetching device data from API: (get_device: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 77, in _fetch_device_data
    self._device = await self._api_client.get_device(self._panasonic_device_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 121, in get_device
    json_response = await self.execute_get(self._get_device_status_url(device_info.guid), "get_device", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 140, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_device: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}
2024-08-09 00:54:45.288 ERROR (MainThread) [custom_components.panasonic_cc.pcomfortcloud.helpers] Error in get_todays_energy
Expected status code '200' but received '403'
Payload: {'deviceGuid': 'B858821474', 'dataMode': 2, 'date': '20240809', 'osTimezone': '+02:00'}
Response body: {"code":4300,"message":"Have no authority to the request"}
2024-08-09 00:54:45.289 ERROR (MainThread) [custom_components.panasonic_cc.coordinator] Error fetching energy data from API: (get_todays_energy: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 136, in _fetch_device_data
    self._energy = await self._api_client.async_get_energy(self._panasonic_device_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 130, in async_get_energy
    todays_item = await self._async_get_todays_energy(device_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 153, in _async_get_todays_energy
    history = await self.execute_post(self._get_device_history_url(), payload, "get_todays_energy", 200)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 114, in execute_post
    await check_response(response, function_description, expected_status_code, payload=json_data)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_todays_energy: Expected status code 200, received: 403: {"code":4300,"message":"Have no authority to the request"}
```

I suspect this is related to having "Enable Daily Energy Sensors" option set.

**Comment by maurilloh** [comment]
Home Assistant Core
2024-08-09 01:30:26.634 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration panasonic_cc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-09 01:30:37.325 INFO (MainThread) [custom_components.panasonic_cc]
https://github.com/sockless-coding/panasonic_cc/issues
2024-08-09 01:30:37.327 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Starting Session
2024-08-09 01:30:37.343 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Loaded settings from '/root/.panasonic-settings'
2024-08-09 01:30:37.347 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Access token is valid
2024-08-09 01:30:38.234 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: {"a2wStatus":{"statusCode":200},"uiFlg":false,"groupCount":1,"groupList":[{"groupId":1033015,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"B192346444","deviceType":"2","deviceName":"casa","connectionStatus":0,"operationMode":1,"zoneStatus":[{"zoneId":1,"operationStatus":0,"temperature":23},{"zoneId":2}],"tankStatus":{"operationStatus":1,"temperature":44}}]}]}
2024-08-09 01:30:38.234 INFO (MainThread) [custom_components.panasonic_cc] Got 0 devices

**Comment by maurilloh** [comment]
i have a water pump and 4 air conditioner, in the versione 1.0.58 i can see them

**Comment by sockless-coding** [comment]
@maurilloh the logs you provided only shows what looks like an aquarea device.

**Comment by ddemarch** [comment]
With version 1.1.7 it works! Thanks!

**Comment by GennaroRASP** [comment]
Good morning,
many thanks for the development and update of the module, but since the update to the 1.1.7 release I receive the following error:
Registratore: custom_components.panasonic_cc.coordinator
Fonte: custom_components/panasonic_cc/coordinator.py:86
Integrazione: Panasonic Comfort Cloud ([documentazione](https://github.com/sockless-coding/panasonic_cc/), [problemi](https://github.com/sockless-coding/panasonic_cc/issues))
Prima occorrenza: 08:50:41 (4 occorrenze)
Ultima registrazione: 10:32:54

Error fetching device data from API: (try_update: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 86, in _fetch_device_data
    if await self._api_client.try_update_device(self._device):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 126, in try_update_device
    json_response = await self.execute_get(self._get_device_status_url(device_guid), "try_update", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 144, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (try_update: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}

Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.panasonic_cc.coordinator
Fonte: helpers/update_coordinator.py:386
Integrazione: Panasonic Comfort Cloud (documentazione, problemi)
Prima occorrenza: 08:50:41 (4 occorrenze)
Ultima registrazione: 10:32:54

Error fetching Panasonic Device Coordinator data: Invalid response from API: (try_update: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}

since I have some automations that warn me when the machine is unavailable, the notification starts, but after a second it returns to being reachable. How can I avoid the inconvenience, thank you very much

**Comment by sockless-coding** [comment]
@GennaroRASP Hi, the 5005 Adapter Communication error is usually caused when the Panasonic Servers cant reach the HVAC, you could go over your wifi settings and see if something is interfering / switching channels.
Or you can change the update interval of the integration to something higher to see if helps

**Comment by ParadiseComputing** [comment]
Hello,
Also getting "Failed setup, will retry: Invalid response from API: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}" when updating to 1.1.7

Logger: custom_components.panasonic_cc.coordinator
Source: custom_components/panasonic_cc/coordinator.py:77
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 10:27:56 (14 occurrences)
Last logged: 10:32:11
Error fetching device data from API: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 77, in _fetch_device_data
    self._device = await self._api_client.get_device(self._panasonic_device_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 121, in get_device
    json_response = await self.execute_get(self._get_device_status_url(device_info.guid), "get_device", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 144, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}

I can control and HVAC systems fine via the Comfort Cloud app.

**Comment by sockless-coding** [comment]
Regarding the 5005 or 5002 error codes, Panasonic's support answer to that is:
"If you receive this error, please check if the Internet environment is stable. If the problem persists even though the Internet is stable, contact your local service center here."

**Comment by aldebaran-ms** [comment]
My two pence here about the 5005 problem. I had the very same problem and it was related with one single unit not being reachable from the Panasonic app. Once I removed the faulty ac unit from the app the HA integration started working again.
BTW thank you all for the great work here!

**Comment by sockless-coding** [comment]
I've made v1.1.8 more resilient in the start-up phase, if it encounters an inaccessible device it will be logged, but the rest should be added.
