### ISSUE TITLE
Adapter Communication Error

### ISSUE THREAD

**Issue by simonhq** [sockless-coding/panasonic_cc#31]
Hi

On a restart today, my connection to two of my Panasonic Air-Conditioners started giving the following error:

`2021-03-20 12:15:34 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139782777837312] Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/panasonic.py", line 21, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 346, in set_device
    self._api.set_device(
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 389, in set_device
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/config/custom_components/panasonic_cc/climate.py", line 126, in async_set_hvac_mode
    await self._api.turn_off()
  File "/config/custom_components/panasonic_cc/panasonic.py", line 227, in turn_off
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 24, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 346, in set_device
    self._api.set_device(
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 389, in set_device
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}`

Any support would be appreciated.

Simon.

**Comment by sockless-coding** [comment]
@simonhq As far as I can tell that error usually indicates an error on Panasonic's end.
So just waiting a bit and retrying usually solves the problem.
Do you still have this issue? If so does the app see all your devices correctly?

**Comment by shyne99** [comment]
Adapter error reflects an error between the Wi-Fi module attached to your hp, and Panasonic server. Nothing can really be done from the integration side to prevent this from happening. It is usually very rare and resolves by its own. 

Check that your module has enough Wi-Fi signal where it is located, it may explain this.

**Comment by Janneurban** [comment]
I think I might have a solution to parts of your problem, today integrated my 3 Panasonic heat pumps to Home Assistant, 1 & 2 were perfectly integrated, the 3 was shown on the Home Asistant instrument panel but was impossible to maneuver and I got the code when trying to maneuver "Invalid response, status code: 500 - Data: {"message": "Adapter Communication error", "code": 5005}. It turned out in my case that the account that used for Home Assistant which incidentally previously belonged to another former resident in the property only had access to heat pump 1 & 2 but simply did not have access in the app comfort cloud to this heat pump number 3, when I well created competency it worked. I was so happy when it worked so I felt I wanted to tell this and hopefully possibly help someone else in the same situation.
