### ISSUE TITLE
Support for Aquarea devices

### ISSUE THREAD

**Issue by sockless-coding** [sockless-coding/panasonic_cc#310]
To add support for Aquarea devices I need help.
Version 2024.9.1 has some extra logging that provides some extra logs that I need before I can add the support.

There should now be several new warning logs looking like:
```
Found 2 unknown device(s):
{...}
{...}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
```
```
Got aquarea device info for: {...}:
{...}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
```

**Comment by stevocz** [comment]
new log from 2024.9.3

```
2024-09-26 10:12:44.063 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Starting Session
2024-09-26 10:12:44.099 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Loaded settings from '/root/.panasonic-settings'
2024-09-26 10:12:44.100 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Access token is not valid
2024-09-26 10:12:44.101 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicauthentication] Refreshing token
2024-09-26 10:12:44.999 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Access token is valid
2024-09-26 10:12:44.999 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.ccappversion] Fetching latest app version from play store
2024-09-26 10:12:45.003 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Saved settings to '/root/.panasonic-settings'
2024-09-26 10:12:45.281 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.ccappversion] Found app version: 1.21.1
2024-09-26 10:12:45.286 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Saved settings to '/root/.panasonic-settings'
2024-09-26 10:12:46.175 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: {"a2wStatus":{"statusCode":200},"uiFlg":false,"groupCount":1,"groupList":[{"groupId":1552406,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"B123456789","deviceType":"2","deviceName":"Doma","connectionStatus":0,"operationMode":1,"zoneStatus":[{"zoneId":1,"operationStatus":0,"temperature":0},{"zoneId":2}],"tankStatus":{"operationStatus":1,"temperature":50}}]}]}
2024-09-26 10:12:46.175 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Found 1 unknown device(s):
{"deviceGuid": "B123456789", "deviceType": "2", "deviceName": "Doma", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 0, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 50}}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
2024-09-26 10:12:46.354 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Failed to get aquarea device info for B123456789
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 121, in check_aquarea
aqua_device = await self.get_aquarea_device(device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 186, in get_aquarea_device
device_id = id_response.cookies.get("selectedDeviceId").value
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-09-26 10:12:46.377 DEBUG (MainThread) [custom_components.panasonic_cc.config_flow] Not devices found
```

**Comment by akc-kyiv** [comment]
Another log for Aquarea Heat Pump

```
Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:118
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 14:37:40 (2 occurrences)
Last logged: 14:39:15
Found 1 unknown device(s): {"deviceGuid": "B625308938", "deviceType": "2", "deviceName": "\u0422\u041d", "connectionStatus": 0, "operationMode": 2, "zoneStatus": [{"zoneId": 1, "operationStatus": 0, "temperature": 14}, {"zoneId": 2, "operationStatus": 0, "temperature": 18}], "tankStatus": {"operationStatus": 1, "temperature": 47}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
```

```
Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:124
integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 14:37:40 (2 occurrences)
Last logged: 14:39:15
Failed to get aquarea device info for B625308938 Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by panmanvk** [comment]
Home assistant give me the following errors:

Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:118
integration: panasonic_cc ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 11:19:51 PM (2 occurrences)
Last logged: 11:28:34 PM

Found 1 unknown device(s): {"deviceGuid": "B029605707", "deviceType": "2", "deviceName": "Casa", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 0, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 48}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310




This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:124
integration: panasonic_cc (documentation, issues)
First occurred: 11:19:51 PM (2 occurrences)
Last logged: 11:28:34 PM

Failed to get aquarea device info for B029605707 Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

Thanks

**Comment by DavidMenting** [comment]
For a WH-MDC09J3E5 air to water heatpump I get the following response:

```Found 1 unknown device(s): {"deviceGuid": "B967354086", "deviceType": "2", "deviceName": "Pana 9kW", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 18}, {"zoneId": 2}], "tankStatus": {}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310 ```

**Comment by bauwelp-awv** [comment]
WH-SDC0709J3E5 air to water heatpump

Found 1 unknown device(s): {"deviceGuid": "B216834177", "deviceType": "2", "deviceName": "Koralowa", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 25}, {"zoneId": 2}], "tankStatus": {"operationStatus": 0, "temperature": 50}}

**Comment by nianj** [comment]
WH-SDC09H3E5 + WH-UD09HE5 (one is the name of the outside unit, the other the unit inhouse. I don't know which is relevant for you)

Found 1 unknown device(s): {"deviceGuid": "B560329121", "deviceType": "2", "deviceName": "Aquarea 9k", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 52}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310

**Comment by c4weddell** [comment]
For a WH-MDC07J3E5 air to water heatpump I get the following response:

`Found 1 unknown device(s): {"deviceGuid": "B156470826", "deviceType": "2", "deviceName": "Our ASHP", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 55}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310`

**Comment by SirGorn** [comment]
Panasonic Aquarea M heat pump

Found 1 unknown device(s): {"deviceGuid": "B084363150", "deviceType": "2", "deviceName": "Panas M", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 29}, {"zoneId": 2}], "tankStatus": {"operationStatus": 0, "temperature": 45}}

**Comment by jakubdusek** [comment]
For B635717730 i get this logs.

This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:124
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 1:03:29 PM (1 occurrences)
Last logged: 1:03:29 PM

Failed to get aquarea device info for B635717730 Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'


and


This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:118
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 1:03:29 PM (1 occurrences)
Last logged: 1:03:29 PM

Found 1 unknown device(s): {"deviceGuid": "B635717730", "deviceType": "2", "deviceName": "U Du\u0161k\u016f", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 53}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310

**Comment by KrzysztofMaciejewski** [comment]
Hi - no devices problem - please help :)

log:
`2024-11-09 13:42:51.588 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Found 1 unknown device(s):
{"deviceGuid": "B194694239", "deviceType": "2", "deviceName": "S31", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 0}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 45}}
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
2024-11-09 13:42:51.751 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Failed to get aquarea device info for B194694239
Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'`

**Comment by pvameln** [comment]
No Devise found by Login 

Found 1 unknown device(s): {"deviceGuid": "B306587586", "deviceType": "2", "deviceName": "WP_Aquarea", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 1}, {"zoneId": 2}], "tankStatus": {}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310

Second Warning

Failed to get aquarea device info for B306587586 Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by dneimanis** [comment]
Unable to add integration, getting this in the logs:

This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:118
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 14:52:06 (7 occurrences)
Last logged: 20:06:11

Found 1 unknown device(s): {"deviceGuid": "B328033601", "deviceType": "2", "deviceName": "Heat pump", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 22}, {"zoneId": 2}], "tankStatus": {}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310

**Comment by pribasv** [comment]
No devices found for Aquarea Heat Pump:

`Este error se originó a partir de una integración personalizada.

Registrador: custom_components.panasonic_cc.pcomfortcloud.apiclient
Fuente: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:124
integración: Panasonic Comfort Cloud (documentación, problemas)
Ocurrió por primera vez: 09:51:25 (2 ocurrencias)
Última vez registrado: 13:44:00

Failed to get aquarea device info for B981155477 Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'`

`Este error se originó a partir de una integración personalizada.

Registrador: custom_components.panasonic_cc.pcomfortcloud.apiclient
Fuente: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:118
integración: Panasonic Comfort Cloud (documentación, problemas)
Ocurrió por primera vez: 09:51:24 (2 ocurrencias)
Última vez registrado: 13:43:59

Found 1 unknown device(s): {"deviceGuid": "B981155477", "deviceType": "2", "deviceName": "Casa", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 1, "temperature": 55}, {"zoneId": 2}], "tankStatus": {"operationStatus": 0, "temperature": 50}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310`

**Comment by Max6025** [comment]
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Quelle: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:124
Integration: Panasonic Comfort Cloud (Dokumentation, Probleme)
Erstmals aufgetreten: 15:49:23 (3 Vorkommnisse)
Zuletzt protokolliert: 15:51:39

Failed to get aquarea device info for B926575037 Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by pablo-cascales** [comment]
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.panasonic_cc.pcomfortcloud.apiclient
Fuente: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:123
integración: Panasonic Comfort Cloud (documentación, problemas)
Ocurrió por primera vez: 04:09:25 (2 ocurrencias)
Última vez registrado: 04:10:55

Found 1 unknown device(s): {"deviceGuid": "B933913411", "deviceType": "2", "deviceName": "Aquarea", "connectionStatus": 0, "operationMode": 1, "zoneStatus": [{"zoneId": 1, "operationStatus": 0, "temperature": 23}, {"zoneId": 2}], "tankStatus": {"operationStatus": 1, "temperature": 48}} Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310

**Comment by flix4f** [comment]
Logfile for an Aquarea AIO:

This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.apiclient
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:129
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: January 9, 2025 at 2:40:13 PM (1 occurrences)
Last logged: January 9, 2025 at 2:40:13 PM

Failed to get aquarea device info for a2w37815 Submit this log to https://github.com/sockless-coding/panasonic_cc/issues/310
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 129, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 194, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by sockless-coding** [comment]
Give version 2025.1.1 a try I've added basic support for Aquarea devices.
Since I don't have access to a Aquarea device myself, I would like to get some feedback if it's working.

**Comment by flix4f** [comment]
After the 2025.1.2 update the Aquarea device is found and appears with three entities. Climate, Water heater and Temperature outside sensor. Also no problems with the other integration that I was already running (Comfort Cloud). Neither one seems to log out the other one.
Similar to the previous integration, the device becomes unavailable from time to time, which I assume has to do with a timed logout from the cloud service.
![image](https://github.com/user-attachments/assets/a5ec9235-1519-44a8-a3b8-cf4d8b379079)

**Comment by pkaras62a** [comment]
Most of the time the climate entities settings on aquarea heat pump have no effect, even when changed, they revert back after refreshing. Despite enabling debug log, this is the only info:
2025-01-13 22:58:25.813 DEBUG (MainThread) [custom_components.panasonic_cc.coordinator] Finished fetching Aquarea Device Coordinator data in 0.805 seconds (success: True)

**Comment by pkaras62a** [comment]
And an attempt to use Panasonic Comfort Cloud app on a mobile gives these entries immediately in the log:
```
2025-01-13 23:16:15.382 WARNING (MainThread) [aioaquarea] <aioaquarea.core.Client object at 0x7f9e66eca660>: Auth Error: 1001-0001 - You have been logged out due to inactivity. Please log in again..
2025-01-13 23:16:15.382 WARNING (MainThread) [aioaquarea] <aioaquarea.core.Client object at 0x7f9e66eca660>: Trying to login again.
```

Seems like integration session is logged out when the app session logs in.

**Comment by svartpippi** [comment]
I have a Aquarea Air-to-water heat pump
Panasonic High Performance 9Kw Mono bloc
Model no: WH-MDC09J3E5
Reachable and controllable from the Panasonic Comfort Cloud application.
I also have 3 air-to-air heatpumps also in the Panasonic Comfort Cloud app:
CZ25ZKE   named "Garaget"
TZ25ZKE   named "Våning1"
TZ25ZKE   named "Våning2"
When I Enabled debugging and reload the integration in home assistant I get this:
2025-06-25 22:35:39.890 WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2025-06-25 22:35:52.510 INFO (MainThread) [custom_components.panasonic_cc] Got 3 devices
2025-06-25 22:35:54.405 DEBUG (MainThread) [custom_components.panasonic_cc.coordinator] Garaget Device features
Nanoe: False
Eco Navi: False
AI Eco: False
2025-06-25 22:35:54.405 DEBUG (MainThread) [custom_components.panasonic_cc.coordinator] Finished fetching Panasonic Device Coordinator data in 1.893 seconds (success: True)
2025-06-25 22:35:55.839 DEBUG (MainThread) [custom_components.panasonic_cc.coordinator] Våning1 Device features
Nanoe: True
Eco Navi: False
AI Eco: False
2025-06-25 22:35:55.839 DEBUG (MainThread) [custom_components.panasonic_cc.coordinator] Finished fetching Panasonic Device Coordinator data in 1.434 seconds (success: True)
2025-06-25 22:35:57.815 DEBUG (MainThread) [custom_components.panasonic_cc.coordinator] Våning2 Device features
Nanoe: True
Eco Navi: False
AI Eco: False
2025-06-25 22:35:57.816 DEBUG (MainThread) [custom_components.panasonic_cc.coordinator] Finished fetching Panasonic Device Coordinator data in 1.976 seconds (success: True)
2025-06-25 22:35:57.928 WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

I get the 3 air-to-air heatpumps in the integration but the air-to-water heat pump is not added.

Is this a known error?

**Comment by kublerlaci** [comment]
# Unsupported Device Type "2" - Panasonic WH-MDC12-16H6E5

## Device Information
- **Model:** Panasonic WH-MDC12-16H6E5 (Aquarea heat pump with hot water tank)
- **WiFi Module:** CZ-TAW1
- **Device Name in App:** Kubler
- **Device GUID:** B734451041
- **Device Type:** 2 (currently unsupported)

## Problem Description
The integration fails to recognize my Panasonic heat pump. The device is visible and fully controllable in the official Panasonic Comfort Cloud mobile app, but the Home Assistant integration reports "No devices found" during setup.

## Integration Version
- **Tested versions:** 2025.5.0, 2025.1.2, 2024.11.0
- **Home Assistant Version:** 2025.x
- **Installation method:** HACS

## Error Logs

### Main Error
```
Could not find any Panasonic Comfort Cloud Heat Pumps
```

### Unknown Device Detection
```
Found 1 unknown device(s): {
  "deviceGuid": "B734451041", 
  "deviceType": "2", 
  "deviceName": "Kubler", 
  "connectionStatus": 0, 
  "operationMode": 1, 
  "zoneStatus": [
    {"zoneId": 1, "operationStatus": 1, "temperature": 100}, 
    {"zoneId": 2}
  ], 
  "tankStatus": {
    "operationStatus": 1, 
    "temperature": 52
  }
}
```

### Aquarea API Error
```
Failed to get aquarea device info for B734451041
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 124, in check_aquarea
    aqua_device = await self.get_aquarea_device(device)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 189, in get_aquarea_device
    device_id = id_response.cookies.get("selectedDeviceId").value
AttributeError: 'NoneType' object has no attribute 'value'
```

## Expected Behavior
The integration should recognize the device and create appropriate climate entities for:
- Heat pump control (heating/cooling modes)
- Temperature control for zones
- Hot water tank control
- Current temperature sensors

## Additional Information
- The device has **2 zones** (zoneStatus shows zoneId: 1 and 2)
- The device includes a **hot water tank** (tankStatus present)
- Device is **online and working** in the official app (connectionStatus: 0)
- All zones and tank are **operational** (operationStatus: 1)

## Request
Could you please add support for `deviceType: "2"`? This appears to be an Aquarea heat pump with integrated hot water tank and multi-zone capability.

I'm happy to provide any additional information, logs, or testing if needed to help implement this feature.

Thank you for your excellent work on this integration!

**Comment by muscaglar** [comment]
**RAC Solo owners: I've got this working (separate integration)**

Bit of a saga, but posting here since this thread is where I ended up when my RAC Solo wouldn't show up in anything.

Turns out these units aren't in Comfort Cloud at all, nor the old Aquarea Smart Cloud. The Aquarea Home app is actually a rebadged Innova app (built by a company called SolutionTech), and it talks to a completely separate backend at `api.aquarea-home.solutiontech.tech`. So panasonic_cc was never going to find them - the device list on the accsmart side is literally empty for these accounts. Verified that myself before digging further.

Pulled the Android APK apart over a weekend and mapped the protocol - REST for login/account stuff, gRPC for live status and control. The RAC Solo is essentially an Innova 2.0 under the hood ("duepuntozero" in the protobuf, which was a nice touch).

Ended up writing a standalone integration: https://github.com/muscaglar/ha-aquarea-home

Working so far on my unit: climate entity with proper mode/fan/setpoint control (it even pulls the min/max/step from the device), room temp sensor, wifi signal. Installable through HACS as a custom repo.

Few things worth knowing:

- No local API on these. I port-scanned the whole range - the wifi module is outbound only, so cloud is the only option.
- If you signed into the app with Apple or Google, password login won't work until you set one via the reset flow.
- Only tested on one RAC Solo so far. Innova 2.0 owners, would be curious if it works for you - should be identical.

Full protocol notes are in PROTOCOL.md in the repo if the maintainer here fancies adding Aquarea Home support natively - happy to share whatever else I've got.

**Comment by sockless-coding** [comment]
This should work in the latest version

**Comment by achillecalegari** [comment]
For RAC Solo / Aquarea Home owners landing here (the Solution Tech cloud, not Comfort Cloud): besides @muscaglar's integration there is now also https://github.com/achillecalegari/hass-innova-cloud, which covers the same v2 cloud with a brand selector (Panasonic Aquarea Home, Innova, DiffusApp, Rhoss Tema, Etherma) and a live event stream. Posting only so this thread stays a useful landing page; nothing to do with Comfort Cloud itself.
