### ISSUE TITLE
Precondition failed 

### ISSUE THREAD

**Issue by drforno** [sockless-coding/panasonic_cc#337]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

2024.11.0

### Describe the issue

From November 7th I have an error in the plugin while authenticating with the cloud.

```
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 7 novembre 2024 alle ore 21:18:53 (1 occurrences)
Last logged: 7 novembre 2024 alle ore 21:18:53

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 76, in async_setup_entry
    await api.start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 62, in start_session
    await super().start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 52, in start_session
    await self._authentication.authenticate(self._username, self._password)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 68, in authenticate
    await self._retrieve_client_acc()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 263, in _retrieve_client_acc
    await check_response(response, 'get_acc_client_id', 200)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_acc_client_id: Expected status code 200, received: 412: {
  "code":41201,
  "message":"Precondition Failed"
```

Today I've tried to re-enter my credential (they are working on the app), but I have another error

### Error/Debug Logs

```text
This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.helpers
Source: custom_components/panasonic_cc/pcomfortcloud/helpers.py:27
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 7 novembre 2024 alle ore 21:18:53 (3 occurrences)
Last logged: 12:18:44

Error in get_acc_client_id Expected status code '200' but received '412' Response body: { "code":41201, "message":"Precondition Failed" }
```

**Comment by dardour7** [comment]
Hi,
The same problem since november 5th.
I thought I saw posts saying it was resolved, but I don't know how because it's not resolved for me.
please help us :-)

best regards

**Comment by drforno** [comment]
I've just updated plugin to 2024-11 and the problem seems resolved.

**Comment by dardour7** [comment]
guys thanks you are too strong.

It's OK

**Comment by vaibhavratnaparkhi** [comment]
Give me 'no devices ' error
![Screenshot_2024-11-08-16-35-44-70_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/cd46a11d-bcae-4555-8e0c-0ebca40502fe)

**Comment by magnusdunker** [comment]
Absolutely brilliant. Thanks for all the hard work
