### ISSUE TITLE
Many errors in HA log

### ISSUE THREAD

**Issue by mkz212** [sockless-coding/panasonic_cc#346]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.12.0

### Describe the issue

# Error 1

```
custom_components.panasonic_cc.pcomfortcloud.panasonicsession
Source: custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py:113
Integration: Panasonic Comfort Cloud

POST url: https://accsmart.panasonic.com/deviceHistoryData, data: {'deviceGuid': 'CS-Z50VKEW+00000000', 'dataMode': 2, 'date': '20241205', 'osTimezone': '+02:00'}
```

# Error 2

```
Source: custom_components/panasonic_cc/coordinator.py:139

Error fetching energy data from API: Cannot connect to host accsmart.panasonic.com:443 ssl:default [Connect call failed ('13.227.146.60', 443)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
        current_loop, exceptions, addrinfo, local_addr_infos
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 101] Connect call failed ('13.227.146.60', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 97, in execute_post
    response = await self._client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1124, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host accsmart.panasonic.com:443 ssl:default [Connect call failed ('13.227.146.60', 443)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 139, in _fetch_device_data
    if await self._api_client.async_try_update_energy(self._energy):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 205, in async_try_update_energy
    todays_item = await self._async_get_todays_energy(energy.info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 222, in _async_get_todays_energy
    history = await self.execute_post(self._get_device_history_url(), payload, "get_todays_energy", 200)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 114, in execute_post
    raise exceptions.RequestError(ex)
custom_components.panasonic_cc.pcomfortcloud.exceptions.RequestError: Cannot connect to host accsmart.panasonic.com:443 ssl:default [Connect call failed ('13.227.146.60', 443)]
```

# Error 3

```
Source: helpers/update_coordinator.py:411

Error fetching Panasonic Device Energy Coordinator data: Invalid response from API: Cannot connect to host accsmart.panasonic.com:443 ssl:default [Connect call failed ('13.227.146.60', 443)]
```

# Error 4

```
Source: custom_components/panasonic_cc/pcomfortcloud/helpers.py:27

Error in get_status Expected status code '200' but received '502' Response body: {"message": "Internal server error"}
Error in get_status Expected status code '200' but received '500' Response body: {"code":5005,"message":"Adapter Communication error"}
```

# Error 5
```
Source: custom_components/panasonic_cc/pcomfortcloud/apiclient.py:166

Failed to get live status for device CS-Z50VKEW+0000000000 switching to cached data.
```

**Comment by sockless-coding** [comment]
It's just the Panasonic Servers having issues, nothing we can do about it...
