### ISSUE TITLE
Config Flow Could Not Be Loaded (after uninstall)

### ISSUE THREAD

**Issue by asmi242** [sockless-coding/panasonic_cc#351]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

2024.3.3

### Describe the issue

I have had this integration working for the last couple of years. I successfully added the 2FA some time ago with no issues.  Recently (a couple of months ago), the devices stopped showing up. I decided to reinstall the integration to see if it would fix the issue.

I have downloaded the integration using HACS, and when I try to add it with the config flow I am getting the error and the config flow is not starting:

**Config flow could not be loaded: {"message":"Invalid handler specified"}**

I've tried several times to uninstall and reinstall the integration with the same result. I should note that the Panasonic CC app is still working fine on my phone

Has anyone encountered this before or have any idea what might be causing this? Thanks in advance.

Added homeassisting log below...

### Error/Debug Logs

```text
2024-12-27 12:24:41.579 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.panasonic_cc.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1025, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1058, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/panasonic_cc/config_flow.py", line 32, in <module>
    class FlowHandler(config_entries.ConfigFlow, domain=PANASONIC_DOMAIN):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 130, in FlowHandler
    ) -> config_entries.ConfigFlowResult:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.config_entries' has no attribute 'ConfigFlowResult'
```

**Comment by sockless-coding** [comment]
@asmi242 You need to update your home assistant, I think 2024.5 is the minimum
