### ISSUE TITLE
Unknown error occurred while logging in

### ISSUE THREAD

**Issue by m3ssage** [sockless-coding/panasonic_cc#37]
Since last OS 6.0 update of Home Assistant, Panasonic Comfort Cloud is unable to connect. 
----
After that, there were some more updates but it still did not work (core-2021.6.4, Panasonic Comfort Cloud v1.0.30). I removed the Integration and tried to readd it. While entering my credentials, I get an 'Unknown error occurred' message. 
BTW, the iphone Panasonic Comfort Cloud app does work using the same credentials..
====================
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/panasonic_cc/config_flow.py:44
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 2:43:34 PM (2 occurrences)
Last logged: 2:47:18 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/panasonic_cc/config_flow.py", line 85, in async_step_user
    return await self._create_device(user_input[CONF_USERNAME], user_input[CONF_PASSWORD])
  File "/config/custom_components/panasonic_cc/config_flow.py", line 74, in _create_device
    return await self._create_entry(username, password)
  File "/config/custom_components/panasonic_cc/config_flow.py", line 44, in _create_entry
    if entry.data[KEY_DOMAIN] == PANASONIC_DOMAIN:
KeyError: 'domain'

**Comment by bradleyscott** [comment]
I get the same error. Did you have any luck identifying the cause?
