### ISSUE TITLE
Does not work with air to water heat pump

### ISSUE THREAD

**Issue by eliashe92** [sockless-coding/panasonic_cc#38]
Hi I have a Panasonic WH-MXC12H9E9 air to water heat pump. I got the integration into home assistant but no values was sent from the heat pump. I have set up the panasonic app and it work fine, giving outdoor temperature, set point and consuption data

**Comment by Th3M1k3y** [comment]
Maybe something has changed with their cloud. The integration does not work with my air to air heat pump any longer either.

This is in the log.

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/panasonic_cc/__init__.py:79
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 6:11:16 PM (1 occurrences)
Last logged: 6:11:16 PM

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 172, in get_devices
    self.login()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```
