### ISSUE TITLE
Cannot set Swing Mode

### ISSUE THREAD

**Issue by garmck** [sockless-coding/panasonic_cc#4]
Hi, thanks for creating this awesome integration. Its working well. 
But I have one issues, when trying trying to set swing mode via an automation or service call directly in HASS the command does not trigger and the following error is generated.

` Error executing script. Unexpected error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 623, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/config/custom_components/panasonic_cc/climate.py", line 134, in async_set_swing_mode
    await self.set_swing_mode(swing_mode)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 426, in set_swing_mode
    raise NotImplementedError()
NotImplementedError`

Any ideas? All other features are working.
Thanks.

**Comment by sockless-coding** [comment]
Hi, 
there was a bug in the set swing mode but I've corrected it so in v1.0.10 you can set the up / down swing mode. 
I'm going to add support for the Left/Right Modes in a later release.

**Comment by garmck** [comment]
Perfect, working fine now 👍 
Left/Right mode would be amazing.
Thanks once again for your time doing this!
