### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by verstrepeng** [sockless-coding/panasonic_cc#53]
Getting this error since today :
```
Logger: homeassistant.config_entries
Source: custom_components/panasonic_cc/__init__.py:79
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 8:32:42 (1 occurrences)
Last logged: 8:32:42

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 172, in get_devices
    self.login()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 502 - Data: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

**Comment by amirandola** [comment]
I think it's a server side problem. Even Panasonic Android app didn't work.
Now both (HA integration and app) work!

**Comment by verstrepeng** [comment]
Indeed, working again... Many thanks
