### ISSUE TITLE
500 - Data: {"message":"Adapter Communication error","code":5005}

### ISSUE THREAD

**Issue by bartasp** [sockless-coding/panasonic_cc#66]
Hello,

Adapter working fine but is not able to communicate via HA.

Any idea what is wrong?

Failed to call service climate/set_hvac_mode. Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}

**Comment by Fonsos** [comment]
Same error here, I have installed it 5 minutes ago via HACS, and it shows the pump as Off and in the app is On.
When I try to turn it on it shows the same error.
Here are the details of the error:
`[140411305791344] Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/panasonic.py", line 21, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 346, in set_device
    self._api.set_device(
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 389, in set_device
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/panasonic_cc/climate.py", line 126, in async_set_hvac_mode
    await self._api.turn_off()
  File "/config/custom_components/panasonic_cc/panasonic.py", line 227, in turn_off
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 24, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 346, in set_device
    self._api.set_device(
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 389, in set_device
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"Adapter Communication error","code":5005}`
