### ISSUE TITLE
Randomly getting error

### ISSUE THREAD

**Issue by nelsongraca** [sockless-coding/panasonic_cc#70]
Hi, I'm getting this error randomly when trying to change the state of my ACs, and temperatures are not properly updating I assume due to this error, anyone else experience this?

    2022-03-13 16:29:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139695595371632] Invalid response, status code: 500 - Data: {"message":"PCPF Communication error","code":5003}
    Traceback (most recent call last):
      File "/config/custom_components/panasonic_cc/panasonic.py", line 21, in wrapper_call
        func(*args, **kwargs)
      File "/config/custom_components/panasonic_cc/panasonic.py", line 346, in set_device
        self._api.set_device(
      File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 389, in set_device
        raise ResponseError(response.status_code, response.text)
    pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"PCPF Communication error","code":5003}
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
        await hass.services.async_call(
      File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
        task.result()
      File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
        await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
      File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
        await self.hass.helpers.service.entity_service_call(
      File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
        future.result()  # pop exception if have
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
        await coro
      File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
        await result
      File "/config/custom_components/panasonic_cc/climate.py", line 126, in async_set_hvac_mode
        await self._api.turn_off()
      File "/config/custom_components/panasonic_cc/panasonic.py", line 227, in turn_off
        await self.hass.async_add_executor_job(
      File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/config/custom_components/panasonic_cc/panasonic.py", line 24, in wrapper_call
        func(*args, **kwargs)
      File "/config/custom_components/panasonic_cc/panasonic.py", line 346, in set_device
        self._api.set_device(
      File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 389, in set_device
        raise ResponseError(response.status_code, response.text)
    pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"message":"PCPF Communication error","code":5003}

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
