### ISSUE TITLE
Panasonic Comfort Cloud. Unexpected error creating device.

### ISSUE THREAD

**Issue by blaatunge** [sockless-coding/panasonic_cc#77]
Hi,

I'm trying to install Panasonic Comfort Cloud. The installation through HACS runs without problems.
Finding the integration after restart is no problem.
When i enter the Panasonic ID and password i get the following error message: "Unexpected error creating device."

I'm sure I use the correct ID / password combination as I can log into Comfort Cloud app on my phone.

Home assistant core 2022.7.2
Home assistant os 8.2

LOG:

2022-07-13 21:22:20 ERROR (MainThread) [custom_components.panasonic_cc.config_flow] Unexpected error creating device
Traceback (most recent call last):
File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
devices = await self.hass.async_add_executor_job(api.get_devices)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/pcomfortcloud/session.py", line 172, in get_devices
self.login()
File "/usr/local/lib/python3.10/site-packages/pcomfortcloud/session.py", line 99, in login
self._create_token()
File "/usr/local/lib/python3.10/site-packages/pcomfortcloud/session.py", line 132, in _create_token
raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>

**Comment by bschjoett** [comment]
I have the same issue and now it's not possible to install it from HACS.

**Comment by sockless-coding** [comment]
Fixed in release v1.0.32
