### ISSUE TITLE
Panasonic cloud could not be integrated in HA

### ISSUE THREAD

**Issue by bschjoett** [sockless-coding/panasonic_cc#78]
Denne fejl stammer fra en brugerdefineret integration.

Logger: homeassistant.config_entries
Source: custom_components/panasonic_cc/pcomfortcloud/session.py:153
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 19.53.39 (1 occurrences)
Last logged: 19.53.39

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 193, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 103, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 153, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

I have tried to solve it with the workaround, but it dos not help.

**Comment by sockless-coding** [comment]
Apply the patched version [https://github.com/sockless-coding/panasonic_cc/issues/76#issuecomment-1183476134](https://github.com/sockless-coding/panasonic_cc/issues/76#issuecomment-1183476134)

**Comment by sockless-coding** [comment]
Fixed in release v1.0.32
