### ISSUE TITLE
Nonetype inside temperature causing error

### ISSUE THREAD

**Issue by hanabal2** [sockless-coding/panasonic_cc#83]
the intergration was working until the latest version i updated today 1.0.33.

now i get the following error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 309, in state_attributes
    if self.hvac_action:
  File "/config/custom_components/panasonic_cc/climate.py", line 138, in hvac_action
    and self._api.target_temperature > self._api.inside_temperature
TypeError: '>' not supported between instances of 'float' and 'NoneType'

I guess the new code requires inside temperature, where my unit doesnt support it. it was working until this version. can this be made optional again?

**Comment by sockless-coding** [comment]
Yeah, the new hvac action property assumed inside temperature was available.
It should be fixed in v1.0.34

**Comment by hanabal2** [comment]
Thanks. that fixed it. awesome work
