### ISSUE TITLE
Unexpected error creating device - 429

### ISSUE THREAD

**Issue by Sillanmaki** [sockless-coding/panasonic_cc#98]
Integration stopped working at some point and I tried to reinstall it. Now I get this error when trying to login. What could cause that?

```2023-01-07 12:25:54.320 ERROR (MainThread) [custom_components.panasonic_cc.config_flow] Unexpected error creating device
Traceback (most recent call last):
File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
devices = await self.hass.async_add_executor_job(api.get_devices)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
self.login()
File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 105, in login
self._create_token()
File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 158, in _create_token
raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data:

**Comment by Sillanmaki** [comment]
CC app worked before I logout. Now login do not work so some issue on Panasonic side. I'll close this one.
